package gt.gob.sat.sat_ifi_sipf.models;
// Generated Nov 17, 2022 8:25:34 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import lombok.Builder;

/**
 * SipfArchivosCreditoFiscal generated by hbm2java
 */
@Builder
@Entity
@Table(name="sipf_archivos_credito_fiscal"
    ,schema="sat_ifi_sipf"
)
public class SipfArchivosCreditoFiscal  implements java.io.Serializable {


     private long idArchivo;
     private String nombre;
     private Integer idestado;
     private String comentario;
     private String nitContribuyente;
     private String periodo;
     private String usuarioModifica;
     private Date fechaModifica;
     private String ipModifica;

    public SipfArchivosCreditoFiscal() {
    }

	
    public SipfArchivosCreditoFiscal(long idArchivo) {
        this.idArchivo = idArchivo;
    }
    public SipfArchivosCreditoFiscal(long idArchivo, String nombre, Integer idestado, String comentario, String nitContribuyente, String periodo, String usuarioModifica, Date fechaModifica, String ipModifica) {
       this.idArchivo = idArchivo;
       this.nombre = nombre;
       this.idestado = idestado;
       this.comentario = comentario;
       this.nitContribuyente = nitContribuyente;
       this.periodo = periodo;
       this.usuarioModifica = usuarioModifica;
       this.fechaModifica = fechaModifica;
       this.ipModifica = ipModifica;
    }
   
     @Id 
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name="id_archivo", unique=true, nullable=false)
    public long getIdArchivo() {
        return this.idArchivo;
    }
    
    public void setIdArchivo(long idArchivo) {
        this.idArchivo = idArchivo;
    }

    
    @Column(name="nombre", length=75)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="idestado")
    public Integer getIdestado() {
        return this.idestado;
    }
    
    public void setIdestado(Integer idestado) {
        this.idestado = idestado;
    }

    
    @Column(name="comentario")
    public String getComentario() {
        return this.comentario;
    }
    
    public void setComentario(String comentario) {
        this.comentario = comentario;
    }

    
    @Column(name="nit_contribuyente", length=16)
    public String getNitContribuyente() {
        return this.nitContribuyente;
    }
    
    public void setNitContribuyente(String nitContribuyente) {
        this.nitContribuyente = nitContribuyente;
    }

    
    @Column(name="periodo", length=50)
    public String getPeriodo() {
        return this.periodo;
    }
    
    public void setPeriodo(String periodo) {
        this.periodo = periodo;
    }

    
    @Column(name="usuario_modifica", length=25)
    public String getUsuarioModifica() {
        return this.usuarioModifica;
    }
    
    public void setUsuarioModifica(String usuarioModifica) {
        this.usuarioModifica = usuarioModifica;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecha_modifica", length=29)
    public Date getFechaModifica() {
        return this.fechaModifica;
    }
    
    public void setFechaModifica(Date fechaModifica) {
        this.fechaModifica = fechaModifica;
    }

    
    @Column(name="ip_modifica", length=40)
    public String getIpModifica() {
        return this.ipModifica;
    }
    
    public void setIpModifica(String ipModifica) {
        this.ipModifica = ipModifica;
    }




}


