package gt.gob.sat.sat_ifi_sipf.models;
// Generated Aug 8, 2022 2:25:08 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SipfParametroSistema generated by hbm2java
 */
@Entity
@Table(name = "sipf_parametro_sistema",
        schema = "sat_ifi_sipf"
)
public class SipfParametroSistema implements java.io.Serializable {

    private int id;
    private String name;
    private String value;
    private Integer reference;
    private Integer referenceType;
    private String type;
    private Date modifiedAt;
    private String modifiedBy;
    private String modifiedFrom;
    private String description;
    private String icon;

    public SipfParametroSistema() {
    }

    public SipfParametroSistema(int id, String name, String value, Integer reference, Integer referenceType, String type, Date modifiedAt, String modifiedBy, String modifiedFrom, String description, String icon) {
        this.id = id;
        this.name = name;
        this.value = value;
        this.reference = reference;
        this.referenceType = referenceType;
        this.type = type;
        this.modifiedAt = modifiedAt;
        this.modifiedBy = modifiedBy;
        this.modifiedFrom = modifiedFrom;
        this.description = description;
        this.icon = icon;
    }

    @Id
    @Column(name = "id_param", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @Column(name = "nombre", nullable = false, length = 50)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "valor", nullable = false, length = 30)
    public String getValue() {
        return this.value;
    }

    public void setValue(String value) {
        this.value = value;
    }

    @Column(name = "referencia_valor")
    public Integer getReference() {
        return this.reference;
    }

    public void setReference(Integer reference) {
        this.reference = reference;
    }

    @Column(name = "tipo_referencia")
    public Integer getReferenceType() {
        return this.referenceType;
    }

    public void setReferenceType(Integer referenceType) {
        this.referenceType = referenceType;
    }

    @Column(name = "tipo_nodo", length = 20)
    public String getType() {
        return this.type;
    }

    public void setType(String type) {
        this.type = type;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "fecha_modifica", nullable = false, length = 13)
    public Date getModifiedAt() {
        return modifiedAt;
    }

    public void setModifiedAt(Date modifiedAt) {
        this.modifiedAt = modifiedAt;
    }

    @Column(name = "usuario_modifica", nullable = false, length = 10)
    public String getModifiedBy() {
        return modifiedBy;
    }

    public void setModifiedBy(String modifiedBy) {
        this.modifiedBy = modifiedBy;
    }

    @Column(name = "ip_modifica", nullable = false, length = 40)
    public String getModifiedFrom() {
        return modifiedFrom;
    }

    public void setModifiedFrom(String modifiedFrom) {
        this.modifiedFrom = modifiedFrom;
    }

    @Column(name = "descripcion", nullable = false, length = 50)
    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @Column(name = "icon", nullable = false, length = 25)
    public String getIcon() {
        return this.icon;
    }

    public void setIcon(String icon) {
        this.icon = icon;
    }
}
