package gt.gob.sat.sat_ifi_sipf.models;
// Generated 16/02/2022 12:14:34 PM by Hibernate Tools 4.3.1

import gt.gob.sat.sat_ifi_sipf.dtos.SeccionesCasoDto;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SipfSeccionesCaso generated by hbm2java
 */
@Entity
@Table(name = "sipf_secciones_caso",
        schema = "sat_ifi_sipf"
)
public class SipfSeccionesCaso implements java.io.Serializable {

    private int idCaso;
    private String usuarioModifica;
    private Date fechaModifica;
    private String ipModifica;
    private String jsonSeccion;

    public SipfSeccionesCaso() {
    }

    public SipfSeccionesCaso(int idCaso, String usuarioModifica, Date fechaModifica, String ipModifica, String jsonSeccion) {
        this.idCaso = idCaso;
        this.usuarioModifica = usuarioModifica;
        this.fechaModifica = fechaModifica;
        this.ipModifica = ipModifica;
        this.jsonSeccion = jsonSeccion;
    }

    public SipfSeccionesCaso(SeccionesCasoDto seccion) {
        this.idCaso = seccion.getIdCaso();
        this.jsonSeccion = seccion.getJsonSeccion();
    }

    @Id

    @Column(name = "id_caso", unique = true, nullable = false)
    public int getIdCaso() {
        return this.idCaso;
    }

    public void setIdCaso(int idCaso) {
        this.idCaso = idCaso;
    }

    @Column(name = "usuario_modifica", nullable = false, length = 20)
    public String getUsuarioModifica() {
        return this.usuarioModifica;
    }

    public void setUsuarioModifica(String usuarioModifica) {
        this.usuarioModifica = usuarioModifica;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "fecha_modifica", nullable = false, length = 29)
    public Date getFechaModifica() {
        return this.fechaModifica;
    }

    public void setFechaModifica(Date fechaModifica) {
        this.fechaModifica = fechaModifica;
    }

    @Column(name = "ip_modifica", nullable = false, length = 40)
    public String getIpModifica() {
        return this.ipModifica;
    }

    public void setIpModifica(String ipModifica) {
        this.ipModifica = ipModifica;
    }

    @Column(name = "json_seccion", nullable = false)
    public String getJsonSeccion() {
        return this.jsonSeccion;
    }

    public void setJsonSeccion(String jsonSeccion) {
        this.jsonSeccion = jsonSeccion;
    }

}
