package gt.gob.sat.sat_ifi_sipf.models;
// Generated 1/02/2022 09:25:46 AM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import lombok.Builder;

/**
 * SipfCatDato generated by hbm2java
 */
@Entity
@Builder
@Table(name = "sipf_cat_dato",
        schema = "sat_ifi_sipf"
)
public class SipfCatDato implements java.io.Serializable {

    private int codigo;
    private int codigoDatoPadre;
    private Integer codigoCatalogo;
    private String codigoIngresado;
    private String nombre;
    private String descripcion;
    private Integer estado;
    private String usuarioAgrega;
    private Date fechaAgrega;
    private String usuarioModifica;
    private Date fechaModifica;
    private Set<SipfCatDato> sipfCatDatos = new HashSet<SipfCatDato>(0);

    public SipfCatDato() {
    }

    public SipfCatDato(int codigo) {
        this.codigo = codigo;
    }

    public SipfCatDato(int codigo, int codigoDatoPadre, Integer codigoCatalogo, String codigoIngresado, String nombre, String descripcion, Integer estado, String usuarioAgrega, Date fechaAgrega, String usuarioModifica, Date fechaModifica, Set<SipfCatDato> sipfCatDatos) {
        this.codigo = codigo;
        this.codigoDatoPadre = codigoDatoPadre;
        this.codigoCatalogo = codigoCatalogo;
        this.codigoIngresado = codigoIngresado;
        this.nombre = nombre;
        this.descripcion = descripcion;
        this.estado = estado;
        this.usuarioAgrega = usuarioAgrega;
        this.fechaAgrega = fechaAgrega;
        this.usuarioModifica = usuarioModifica;
        this.fechaModifica = fechaModifica;
        this.sipfCatDatos = sipfCatDatos;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "codigo", unique = true, nullable = false)
    public int getCodigo() {
        return this.codigo;
    }

    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }

    @Column(name = "codigo_dato_padre")
    public int getCodigoDatoPadre() {
        return this.codigoDatoPadre;
    }

    public void setCodigoDatoPadre(int codigoDatoPadre) {
        this.codigoDatoPadre = codigoDatoPadre;
    }

    @Column(name = "codigo_catalogo")
    public Integer getCodigoCatalogo() {
        return this.codigoCatalogo;
    }

    public void setCodigoCatalogo(Integer codigoCatalogo) {
        this.codigoCatalogo = codigoCatalogo;
    }

    @Column(name = "codigo_ingresado")
    public String getCodigoIngresado() {
        return this.codigoIngresado;
    }

    public void setCodigoIngresado(String codigoIngresado) {
        this.codigoIngresado = codigoIngresado;
    }

    @Column(name = "nombre")
    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    @Column(name = "descripcion")
    public String getDescripcion() {
        return this.descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    @Column(name = "estado")
    public Integer getEstado() {
        return this.estado;
    }

    public void setEstado(Integer estado) {
        this.estado = estado;
    }

    @Column(name = "usuario_agrega")
    public String getUsuarioAgrega() {
        return this.usuarioAgrega;
    }

    public void setUsuarioAgrega(String usuarioAgrega) {
        this.usuarioAgrega = usuarioAgrega;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "fecha_agrega", length = 29)
    public Date getFechaAgrega() {
        return this.fechaAgrega;
    }

    public void setFechaAgrega(Date fechaAgrega) {
        this.fechaAgrega = fechaAgrega;
    }

    @Column(name = "usuario_modifica")
    public String getUsuarioModifica() {
        return this.usuarioModifica;
    }

    public void setUsuarioModifica(String usuarioModifica) {
        this.usuarioModifica = usuarioModifica;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "fecha_modifica", length = 29)
    public Date getFechaModifica() {
        return this.fechaModifica;
    }

    public void setFechaModifica(Date fechaModifica) {
        this.fechaModifica = fechaModifica;
    }

}
