package gt.gob.sat.sat_ifi_sipf.models;
// Generated Nov 4, 2022 10:43:26 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import lombok.Builder;

/**
 * SipfHallazgoDenunciaGabinete generated by hbm2java
 */
@Builder
@Entity
@Table(name="sipf_hallazgo_denuncia_gabinete"
    ,schema="sat_ifi_sipf"
)
public class SipfHallazgoDenunciaGabinete  implements java.io.Serializable {


     private int idHallazgo;
     private String correlativo;
     private String nombre;
     private String descripcion;
     private String usuarioModifica;
     private Date fechaModifica;
     private String ipModifica;

    public SipfHallazgoDenunciaGabinete() {
    }

    public SipfHallazgoDenunciaGabinete(int idHallazgo, String correlativo, String nombre, String descripcion, String usuarioModifica, Date fechaModifica, String ipModifica) {
       this.idHallazgo = idHallazgo;
       this.correlativo = correlativo;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.usuarioModifica = usuarioModifica;
       this.fechaModifica = fechaModifica;
       this.ipModifica = ipModifica;
    }
   
    @GeneratedValue(strategy = GenerationType.IDENTITY) 
    @Id     
    @Column(name="id_hallazgo", unique=true, nullable=false)
    public int getIdHallazgo() {
        return this.idHallazgo;
    }
    
    public void setIdHallazgo(int idHallazgo) {
        this.idHallazgo = idHallazgo;
    }

    
    @Column(name="correlativo", nullable=false, length=20)
    public String getCorrelativo() {
        return this.correlativo;
    }
    
    public void setCorrelativo(String correlativo) {
        this.correlativo = correlativo;
    }

    
    @Column(name="nombre", nullable=false, length=300)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="descripcion", nullable=false)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    
    @Column(name="usuario_modifica", nullable=false, length=20)
    public String getUsuarioModifica() {
        return this.usuarioModifica;
    }
    
    public void setUsuarioModifica(String usuarioModifica) {
        this.usuarioModifica = usuarioModifica;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecha_modifica", nullable=false, length=29)
    public Date getFechaModifica() {
        return this.fechaModifica;
    }
    
    public void setFechaModifica(Date fechaModifica) {
        this.fechaModifica = fechaModifica;
    }

    
    @Column(name="ip_modifica", nullable=false, length=40)
    public String getIpModifica() {
        return this.ipModifica;
    }
    
    public void setIpModifica(String ipModifica) {
        this.ipModifica = ipModifica;
    }




}


