package gt.gob.sat.sat_ifi_sipf.models;
// Generated Aug 2, 2022 10:48:36 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SipfPlantillasDocumentos generated by hbm2java
 */
@Entity
@Table(name="sipf_plantillas_documentos"
    ,schema="sat_ifi_sipf"
)
public class SipfPlantillasDocumentos  implements java.io.Serializable {


     private int idPlantilla;
     private String nombre;
     private String catalogos;
     private String encabezado;
     private String piePagina;
     private String usuarioModifica;
     private String ipModificia;
     private Date fechaModifica;

    public SipfPlantillasDocumentos() {
    }

	
    public SipfPlantillasDocumentos(int idPlantilla) {
        this.idPlantilla = idPlantilla;
    }
    public SipfPlantillasDocumentos(int idPlantilla, String nombre, String catalogos, String encabezado, String piePagina, String usuarioModifica, String ipModificia, Date fechaModifica) {
       this.idPlantilla = idPlantilla;
       this.nombre = nombre;
       this.catalogos = catalogos;
       this.encabezado = encabezado;
       this.piePagina = piePagina;
       this.usuarioModifica = usuarioModifica;
       this.ipModificia = ipModificia;
       this.fechaModifica = fechaModifica;
    }
   
    @Id 
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name="id_plantilla", unique=true, nullable=false)
    public int getIdPlantilla() {
        return this.idPlantilla;
    }
    
    public void setIdPlantilla(int idPlantilla) {
        this.idPlantilla = idPlantilla;
    }

    
    @Column(name="nombre", length=200)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="catalogos")
    public String getCatalogos() {
        return this.catalogos;
    }
    
    public void setCatalogos(String catalogos) {
        this.catalogos = catalogos;
    }

    
    @Column(name="encabezado")
    public String getEncabezado() {
        return this.encabezado;
    }
    
    public void setEncabezado(String encabezado) {
        this.encabezado = encabezado;
    }

    
    @Column(name="pie_pagina")
    public String getPiePagina() {
        return this.piePagina;
    }
    
    public void setPiePagina(String piePagina) {
        this.piePagina = piePagina;
    }

    
    @Column(name="usuario_modifica", length=20)
    public String getUsuarioModifica() {
        return this.usuarioModifica;
    }
    
    public void setUsuarioModifica(String usuarioModifica) {
        this.usuarioModifica = usuarioModifica;
    }

    
    @Column(name="ip_modificia", length=20)
    public String getIpModificia() {
        return this.ipModificia;
    }
    
    public void setIpModificia(String ipModificia) {
        this.ipModificia = ipModificia;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecha_modifica", length=29)
    public Date getFechaModifica() {
        return this.fechaModifica;
    }
    
    public void setFechaModifica(Date fechaModifica) {
        this.fechaModifica = fechaModifica;
    }




}


