package gt.gob.sat.sat_ifi_sipf.models;
// Generated 1/02/2022 09:31:58 AM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SipfHistorialComentarios generated by hbm2java
 */
@Entity
@Table(name = "sipf_historial_comentarios",
        schema = "sat_ifi_sipf"
)
public class SipfHistorialComentarios implements java.io.Serializable {

    private int idHistorialComentario;
    private String idRegistro;
    private int idTipoComentario;
    private String comentarios;
    private String usuarioModifica;
    private String ipModifica;
    private Date fechaModifica;

    public SipfHistorialComentarios() {
    }

    public SipfHistorialComentarios(int idHistorialComentario, String idRegistro, int idTipoComentario, String comentarios, String usuarioModifica, String ipModifica, Date fechaModifica) {
        this.idHistorialComentario = idHistorialComentario;
        this.idRegistro = idRegistro;
        this.idTipoComentario = idTipoComentario;
        this.comentarios = comentarios;
        this.usuarioModifica = usuarioModifica;
        this.ipModifica = ipModifica;
        this.fechaModifica = fechaModifica;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id_historial_comentario", unique = true, nullable = false)
    public int getIdHistorialComentario() {
        return this.idHistorialComentario;
    }

    public void setIdHistorialComentario(int idHistorialComentario) {
        this.idHistorialComentario = idHistorialComentario;
    }

    @Column(name = "id_registro", nullable = false)
    public String getIdRegistro() {
        return this.idRegistro;
    }

    public void setIdRegistro(String idRegistro) {
        this.idRegistro = idRegistro;
    }

    @Column(name = "id_tipo_comentario", nullable = false)
    public int getIdTipoComentario() {
        return this.idTipoComentario;
    }

    public void setIdTipoComentario(int idTipoComentario) {
        this.idTipoComentario = idTipoComentario;
    }

    @Column(name = "comentarios", nullable = false)
    public String getComentarios() {
        return this.comentarios;
    }

    public void setComentarios(String comentarios) {
        this.comentarios = comentarios;
    }

    @Column(name = "usuario_modifica", nullable = false, length = 20)
    public String getUsuarioModifica() {
        return this.usuarioModifica;
    }

    public void setUsuarioModifica(String usuarioModifica) {
        this.usuarioModifica = usuarioModifica;
    }

    @Column(name = "ip_modifica", nullable = false, length = 40)
    public String getIpModifica() {
        return this.ipModifica;
    }

    public void setIpModifica(String ipModifica) {
        this.ipModifica = ipModifica;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "fecha_modifica", nullable = false, length = 29)
    public Date getFechaModifica() {
        return this.fechaModifica;
    }

    public void setFechaModifica(Date fechaModifica) {
        this.fechaModifica = fechaModifica;
    }

}
