package gt.gob.sat.sat_ifi_sipf.models;
// Generated 21-sep-2022 12:12:38 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SipfAlcanceDetalle generated by hbm2java
 */
@Entity
@Table(name="sipf_alcance_detalle"
    ,schema="sat_ifi_sipf"
)
public class SipfAlcanceDetalle  implements java.io.Serializable {


     private SipfAlcanceDetalleId id;
     private String detalle;
     private String usuarioModifica;
     private Date fechaModifica;
     private String ipModifica;

    public SipfAlcanceDetalle() {
    }

	
    public SipfAlcanceDetalle(SipfAlcanceDetalleId id, String detalle) {
        this.id = id;
        this.detalle = detalle;
    }
    public SipfAlcanceDetalle(SipfAlcanceDetalleId id, String detalle, String usuarioModifica, Date fechaModifica, String ipModifica) {
       this.id = id;
       this.detalle = detalle;
       this.usuarioModifica = usuarioModifica;
       this.fechaModifica = fechaModifica;
       this.ipModifica = ipModifica;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idAlcance", column=@Column(name="id_alcance", nullable=false) ), 
        @AttributeOverride(name="idSeccion", column=@Column(name="id_seccion", nullable=false) ) } )
    public SipfAlcanceDetalleId getId() {
        return this.id;
    }
    
    public void setId(SipfAlcanceDetalleId id) {
        this.id = id;
    }

    
    @Column(name="detalle", nullable=false)
    public String getDetalle() {
        return this.detalle;
    }
    
    public void setDetalle(String detalle) {
        this.detalle = detalle;
    }

    
    @Column(name="usuario_modifica", length=50)
    public String getUsuarioModifica() {
        return this.usuarioModifica;
    }
    
    public void setUsuarioModifica(String usuarioModifica) {
        this.usuarioModifica = usuarioModifica;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecha_modifica", length=22)
    public Date getFechaModifica() {
        return this.fechaModifica;
    }
    
    public void setFechaModifica(Date fechaModifica) {
        this.fechaModifica = fechaModifica;
    }

    
    @Column(name="ip_modifica")
    public String getIpModifica() {
        return this.ipModifica;
    }
    
    public void setIpModifica(String ipModifica) {
        this.ipModifica = ipModifica;
    }




}


