package gt.gob.sat.sat_ifi_sipf.models;
// Generated Sep 7, 2022 12:27:13 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import lombok.Builder;

/**
 * SipfHistoricoSolicitudCreditoFiscal generated by hbm2java
 */
@Builder
@Entity
@Table(name="sipf_historico_solicitud_credito_fiscal"
    ,schema="sat_ifi_sipf"
)
public class SipfHistoricoSolicitudCreditoFiscal  implements java.io.Serializable {


     private int id;
     private String numeroFormulario;
     private Integer estado;
     private String usuarioModifica;
     private Date fechaModifica;
     private String ipModifica;

    public SipfHistoricoSolicitudCreditoFiscal() {
    }

	
    public SipfHistoricoSolicitudCreditoFiscal(int id) {
        this.id = id;
    }
    public SipfHistoricoSolicitudCreditoFiscal(int id, String numeroFormulario, Integer estado, String usuarioModifica, Date fechaModifica, String ipModifica) {
       this.id = id;
       this.numeroFormulario = numeroFormulario;
       this.estado = estado;
       this.usuarioModifica = usuarioModifica;
       this.fechaModifica = fechaModifica;
       this.ipModifica = ipModifica;
    }
   
     @Id 
     @GeneratedValue(strategy = GenerationType.IDENTITY)    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="numero_formulario")
    public String getNumeroFormulario() {
        return this.numeroFormulario;
    }
    
    public void setNumeroFormulario(String numeroFormulario) {
        this.numeroFormulario = numeroFormulario;
    }

    
    @Column(name="estado")
    public Integer getEstado() {
        return this.estado;
    }
    
    public void setEstado(Integer estado) {
        this.estado = estado;
    }

    
    @Column(name="usuario_modifica")
    public String getUsuarioModifica() {
        return this.usuarioModifica;
    }
    
    public void setUsuarioModifica(String usuarioModifica) {
        this.usuarioModifica = usuarioModifica;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecha_modifica", length=29)
    public Date getFechaModifica() {
        return this.fechaModifica;
    }
    
    public void setFechaModifica(Date fechaModifica) {
        this.fechaModifica = fechaModifica;
    }

    
    @Column(name="ip_modifica")
    public String getIpModifica() {
        return this.ipModifica;
    }
    
    public void setIpModifica(String ipModifica) {
        this.ipModifica = ipModifica;
    }




}


