package gt.gob.sat.sat_ifi_sipf.models;
// Generated 22/08/2022 03:05:10 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SipfDenunciaColaboradorId generated by hbm2java
 */
@Embeddable
public class SipfDenunciaColaboradorId  implements java.io.Serializable {


     private String correlativoDenuncia;
     private String nitResponsable;

    public SipfDenunciaColaboradorId() {
    }

    public SipfDenunciaColaboradorId(String correlativoDenuncia, String nitResponsable) {
       this.correlativoDenuncia = correlativoDenuncia;
       this.nitResponsable = nitResponsable;
    }
   


    @Column(name="correlativo_denuncia", nullable=false, length=20)
    public String getCorrelativoDenuncia() {
        return this.correlativoDenuncia;
    }
    
    public void setCorrelativoDenuncia(String correlativoDenuncia) {
        this.correlativoDenuncia = correlativoDenuncia;
    }


    @Column(name="nit_responsable", nullable=false, length=16)
    public String getNitResponsable() {
        return this.nitResponsable;
    }
    
    public void setNitResponsable(String nitResponsable) {
        this.nitResponsable = nitResponsable;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SipfDenunciaColaboradorId) ) return false;
		 SipfDenunciaColaboradorId castOther = ( SipfDenunciaColaboradorId ) other; 
         
		 return ( (this.getCorrelativoDenuncia()==castOther.getCorrelativoDenuncia()) || ( this.getCorrelativoDenuncia()!=null && castOther.getCorrelativoDenuncia()!=null && this.getCorrelativoDenuncia().equals(castOther.getCorrelativoDenuncia()) ) )
 && ( (this.getNitResponsable()==castOther.getNitResponsable()) || ( this.getNitResponsable()!=null && castOther.getNitResponsable()!=null && this.getNitResponsable().equals(castOther.getNitResponsable()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getCorrelativoDenuncia() == null ? 0 : this.getCorrelativoDenuncia().hashCode() );
         result = 37 * result + ( getNitResponsable() == null ? 0 : this.getNitResponsable().hashCode() );
         return result;
   }   


}


