package gt.gob.sat.sat_ifi_sipf.models;
// Generated 14/06/2022 11:24:19 AM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import lombok.Builder;

/**
 * SipfConsultaCasoJson generated by hbm2java
 */
@Entity
@Builder
@Table(name = "sipf_consulta_caso_json",
        schema = "sat_ifi_sipf"
)
public class SipfConsultaCasoJson implements java.io.Serializable {

    private int idConsultaJson;
    private Integer idCaso;
    private String json;
    private Integer idTipoConsulta;
    private String usuarioModifica;
    private Date fechaModifica;
    private String ipModifica;

    public SipfConsultaCasoJson() {
    }

    public SipfConsultaCasoJson(int idConsultaJson) {
        this.idConsultaJson = idConsultaJson;
    }

    public SipfConsultaCasoJson(int idConsultaJson, Integer idCaso, String json, Integer idTipoConsulta, String usuarioModifica, Date fechaModifica, String ipModifica) {
        this.idConsultaJson = idConsultaJson;
        this.idCaso = idCaso;
        this.json = json;
        this.idTipoConsulta = idTipoConsulta;
        this.usuarioModifica = usuarioModifica;
        this.fechaModifica = fechaModifica;
        this.ipModifica = ipModifica;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)

    @Column(name = "id_consulta_json", unique = true, nullable = false)
    public int getIdConsultaJson() {
        return this.idConsultaJson;
    }

    public void setIdConsultaJson(int idConsultaJson) {
        this.idConsultaJson = idConsultaJson;
    }

    @Column(name = "id_caso")
    public Integer getIdCaso() {
        return this.idCaso;
    }

    public void setIdCaso(Integer idCaso) {
        this.idCaso = idCaso;
    }

    @Column(name = "json")
    public String getJson() {
        return this.json;
    }

    public void setJson(String json) {
        this.json = json;
    }

    @Column(name = "id_tipo_consulta")
    public Integer getIdTipoConsulta() {
        return this.idTipoConsulta;
    }

    public void setIdTipoConsulta(Integer idTipoConsulta) {
        this.idTipoConsulta = idTipoConsulta;
    }

    @Column(name = "usuario_modifica")
    public String getUsuarioModifica() {
        return this.usuarioModifica;
    }

    public void setUsuarioModifica(String usuarioModifica) {
        this.usuarioModifica = usuarioModifica;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "fecha_modifica", length = 13)
    public Date getFechaModifica() {
        return this.fechaModifica;
    }

    public void setFechaModifica(Date fechaModifica) {
        this.fechaModifica = fechaModifica;
    }

    @Column(name = "ip_modifica")
    public String getIpModifica() {
        return this.ipModifica;
    }

    public void setIpModifica(String ipModifica) {
        this.ipModifica = ipModifica;
    }

}
