package gt.gob.sat.sat_ifi_sipf.models;
// Generated 12/09/2022 02:06:58 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SipfCatDatoCondicionEspecial generated by hbm2java
 */
@Entity
@Table(name="sipf_cat_dato_condicion_especial"
    ,schema="sat_ifi_sipf"
)
public class SipfCatDatoCondicionEspecial  implements java.io.Serializable {


     private int codigo;
     private Integer codigoDato;
     private String valor;
     private String nombre;
     private String descripcion;
     private Integer idEstado;
     private String usuarioAgrega;
     private Date fechaAgrega;
     private String usuarioModifica;
     private Date fechaModifica;

    public SipfCatDatoCondicionEspecial() {
    }

	
    public SipfCatDatoCondicionEspecial(int codigo) {
        this.codigo = codigo;
    }
    public SipfCatDatoCondicionEspecial(int codigo, Integer codigoDato, String valor, String nombre, String descripcion, Integer idEstado, String usuarioAgrega, Date fechaAgrega, String usuarioModifica, Date fechaModifica) {
       this.codigo = codigo;
       this.codigoDato = codigoDato;
       this.valor = valor;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.idEstado = idEstado;
       this.usuarioAgrega = usuarioAgrega;
       this.fechaAgrega = fechaAgrega;
       this.usuarioModifica = usuarioModifica;
       this.fechaModifica = fechaModifica;
    }
   
     @Id 

    
    @Column(name="codigo", unique=true, nullable=false)
    public int getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }

    
    @Column(name="codigo_dato")
    public Integer getCodigoDato() {
        return this.codigoDato;
    }
    
    public void setCodigoDato(Integer codigoDato) {
        this.codigoDato = codigoDato;
    }

    
    @Column(name="valor")
    public String getValor() {
        return this.valor;
    }
    
    public void setValor(String valor) {
        this.valor = valor;
    }

    
    @Column(name="nombre")
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="descripcion")
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    
    @Column(name="id_estado")
    public Integer getIdEstado() {
        return this.idEstado;
    }
    
    public void setIdEstado(Integer idEstado) {
        this.idEstado = idEstado;
    }

    
    @Column(name="usuario_agrega")
    public String getUsuarioAgrega() {
        return this.usuarioAgrega;
    }
    
    public void setUsuarioAgrega(String usuarioAgrega) {
        this.usuarioAgrega = usuarioAgrega;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecha_agrega", length=29)
    public Date getFechaAgrega() {
        return this.fechaAgrega;
    }
    
    public void setFechaAgrega(Date fechaAgrega) {
        this.fechaAgrega = fechaAgrega;
    }

    
    @Column(name="usuario_modifica")
    public String getUsuarioModifica() {
        return this.usuarioModifica;
    }
    
    public void setUsuarioModifica(String usuarioModifica) {
        this.usuarioModifica = usuarioModifica;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecha_modifica", length=29)
    public Date getFechaModifica() {
        return this.fechaModifica;
    }
    
    public void setFechaModifica(Date fechaModifica) {
        this.fechaModifica = fechaModifica;
    }




}


