package gt.gob.sat.sat_ifi_sipf.models;
// Generated 21/03/2022 09:26:30 AM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * SipfPerfilUrl generated by hbm2java
 */
@Entity
@Table(name="sipf_perfil_url"
    ,schema="sat_ifi_sipf"
)
public class SipfPerfilUrl  implements java.io.Serializable {


     private SipfPerfilUrlId id;

    public SipfPerfilUrl() {
    }

    public SipfPerfilUrl(SipfPerfilUrlId id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idPerfil", column=@Column(name="id_perfil", nullable=false) ), 
        @AttributeOverride(name="idUrl", column=@Column(name="id_url", nullable=false) ) } )
    public SipfPerfilUrlId getId() {
        return this.id;
    }
    
    public void setId(SipfPerfilUrlId id) {
        this.id = id;
    }




}


