package gt.gob.sat.sat_ifi_sipf.models;
// Generated 17/08/2022 02:42:25 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import lombok.Builder;

/**
 * SipfInsumo generated by hbm2java
 */
@Entity
@Builder
@Table(name = "sipf_insumo",
        schema = "sat_ifi_sipf"
)
public class SipfInsumo implements java.io.Serializable {

    private int idInsumo;
    private String nombreInsumo;
    private Integer idGerencia;
    private String nitEncargado;
    private Integer idEstado;
    private Integer idDepartamento;
    private Integer idTipoInsumo;
    private String usuarioModifica;
    private Date fechaModifica;
    private String ipModifica;
    private Integer idUnidadAdministrativa;
    private String descripcion;
    private String idProceso;
    private Integer idEstadoAnterior;
    private Date fechaPublicacion;

    public SipfInsumo() {
    }

    public SipfInsumo(int idInsumo) {
        this.idInsumo = idInsumo;
    }

    public SipfInsumo(int idInsumo, String nombreInsumo, Integer idGerencia, String nitEncargado, Integer idEstado, Integer idDepartamento, Integer idTipoInsumo, String usuarioModifica, Date fechaModifica, String ipModifica, Integer idUnidadAdministrativa, String descripcion, String idProceso, Integer idEstadoAnterior,Date fechaPublicacion) {
        this.idInsumo = idInsumo;
        this.nombreInsumo = nombreInsumo;
        this.idGerencia = idGerencia;
        this.nitEncargado = nitEncargado;
        this.idEstado = idEstado;
        this.idDepartamento = idDepartamento;
        this.idTipoInsumo = idTipoInsumo;
        this.usuarioModifica = usuarioModifica;
        this.fechaModifica = fechaModifica;
        this.ipModifica = ipModifica;
        this.idUnidadAdministrativa = idUnidadAdministrativa;
        this.descripcion = descripcion;
        this.idProceso = idProceso;
        this.idEstadoAnterior = idEstadoAnterior;
        this.fechaPublicacion = fechaPublicacion;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id_insumo", unique = true, nullable = false)
    public int getIdInsumo() {
        return this.idInsumo;
    }

    public void setIdInsumo(int idInsumo) {
        this.idInsumo = idInsumo;
    }

    @Column(name = "nombre_insumo", length = 100)
    public String getNombreInsumo() {
        return this.nombreInsumo;
    }

    public void setNombreInsumo(String nombreInsumo) {
        this.nombreInsumo = nombreInsumo;
    }

    @Column(name = "id_gerencia")
    public Integer getIdGerencia() {
        return this.idGerencia;
    }

    public void setIdGerencia(Integer idGerencia) {
        this.idGerencia = idGerencia;
    }

    @Column(name = "nit_encargado", length = 15)
    public String getNitEncargado() {
        return this.nitEncargado;
    }

    public void setNitEncargado(String nitEncargado) {
        this.nitEncargado = nitEncargado;
    }

    @Column(name = "id_estado")
    public Integer getIdEstado() {
        return this.idEstado;
    }

    public void setIdEstado(Integer idEstado) {
        this.idEstado = idEstado;
    }

    @Column(name = "id_departamento")
    public Integer getIdDepartamento() {
        return this.idDepartamento;
    }

    public void setIdDepartamento(Integer idDepartamento) {
        this.idDepartamento = idDepartamento;
    }

    @Column(name = "id_tipo_insumo")
    public Integer getIdTipoInsumo() {
        return this.idTipoInsumo;
    }

    public void setIdTipoInsumo(Integer idTipoInsumo) {
        this.idTipoInsumo = idTipoInsumo;
    }

    @Column(name = "usuario_modifica", length = 20)
    public String getUsuarioModifica() {
        return this.usuarioModifica;
    }

    public void setUsuarioModifica(String usuarioModifica) {
        this.usuarioModifica = usuarioModifica;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "fecha_modifica", length = 22)
    public Date getFechaModifica() {
        return this.fechaModifica;
    }

    public void setFechaModifica(Date fechaModifica) {
        this.fechaModifica = fechaModifica;
    }

    @Column(name = "ip_modifica", length = 40)
    public String getIpModifica() {
        return this.ipModifica;
    }

    public void setIpModifica(String ipModifica) {
        this.ipModifica = ipModifica;
    }

    @Column(name = "id_unidad_administrativa")
    public Integer getIdUnidadAdministrativa() {
        return this.idUnidadAdministrativa;
    }

    public void setIdUnidadAdministrativa(Integer idUnidadAdministrativa) {
        this.idUnidadAdministrativa = idUnidadAdministrativa;
    }

    @Column(name = "descripcion", length = 100)
    public String getDescripcion() {
        return this.descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    @Column(name = "id_proceso", length = 200)
    public String getIdProceso() {
        return this.idProceso;
    }

    public void setIdProceso(String idProceso) {
        this.idProceso = idProceso;
    }

    @Column(name = "id_estado_anterior")
    public Integer getIdEstadoAnterior() {
        return this.idEstadoAnterior;
    }

    public void setIdEstadoAnterior(Integer idEstadoAnterior) {
        this.idEstadoAnterior = idEstadoAnterior;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "fecha_publicacion", length = 22)
    public Date getFechaPublicacion() {
        return fechaPublicacion;
    }

    public void setFechaPublicacion(Date fechaPublicacion) {
        this.fechaPublicacion = fechaPublicacion;
    }
}
