package gt.gob.sat.sat_ifi_sipf.models;
// Generated 17/10/2022 03:07:51 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import lombok.Builder;

/**
 * SipfSolicitudesPosteriori generated by hbm2java
 */
@Entity
@Builder
@Table(name = "sipf_solicitudes_posteriori",
        schema = "sat_ifi_sipf"
)
public class SipfSolicitudesPosteriori implements java.io.Serializable {

    private int idSolicitud;
    private Integer idAgrupacion;
    private int idEstado;
    private long noSolicitud;
    private String audiencia;
    private Date fechaAudiencia;
    private String nit;
    private String nombre;
    private String noDuca;
    private String noDucaOrden;
    private String fechaAceptacion;
    private String regimen;
    private String selectivo;
    private String paisProveedor;
    private String tipoAjuste;
    private String expedientes;
    private String certificadoEnsayo;
    private String dictamenArancelaria;
    private Date fechaDictamen;
    private String descripcion;
    private Integer capituloDeclarado;
    private Integer partidaDeclarada;
    private Integer incisosDeclarado;
    private Double tasaDai;
    private Double daiPagado;
    private Double ivaPago;
    private Integer capituloDictaminado;
    private Integer partidaDictaminado;
    private Integer incisoDictaminado;
    private Double tasaDaiDictaminado;
    private String tipoAlertivo;
    private String opinionDace;
    private Double montoTotal;
    private String observaciones;
    private String unidadMedida;
    private Integer cantidad;
    private Double valorDeclarado;
    private Double valorAjustado;
    private String numeroOrden;
    private String tratoArancelario;

    public SipfSolicitudesPosteriori() {
    }

    public SipfSolicitudesPosteriori(int idSolicitud, int idEstado, long noSolicitud) {
        this.idSolicitud = idSolicitud;
        this.idEstado = idEstado;
        this.noSolicitud = noSolicitud;
    }

    public SipfSolicitudesPosteriori(int idSolicitud, Integer idAgrupacion, int idEstado, long noSolicitud, String audiencia, Date fechaAudiencia, String nit, String nombre, String noDuca, String noDucaOrden, String fechaAceptacion, String regimen, String selectivo, String paisProveedor, String tipoAjuste, String expedientes, String certificadoEnsayo, String dictamenArancelaria, Date fechaDictamen, String descripcion, Integer capituloDeclarado, Integer partidaDeclarada, Integer incisosDeclarado, Double tasaDai, Double daiPagado, Double ivaPago, Integer capituloDictaminado, Integer partidaDictaminado, Integer incisoDictaminado, Double tasaDaiDictaminado, String tipoAlertivo, String opinionDace, Double montoTotal, String observaciones, String unidadMedida, Integer cantidad, Double valorDeclarado, Double valorAjustado, String numeroOrden, String tratoArancelario) {
        this.idSolicitud = idSolicitud;
        this.idAgrupacion = idAgrupacion;
        this.idEstado = idEstado;
        this.noSolicitud = noSolicitud;
        this.audiencia = audiencia;
        this.fechaAudiencia = fechaAudiencia;
        this.nit = nit;
        this.nombre = nombre;
        this.noDuca = noDuca;
        this.noDucaOrden = noDucaOrden;
        this.fechaAceptacion = fechaAceptacion;
        this.regimen = regimen;
        this.selectivo = selectivo;
        this.paisProveedor = paisProveedor;
        this.tipoAjuste = tipoAjuste;
        this.expedientes = expedientes;
        this.certificadoEnsayo = certificadoEnsayo;
        this.dictamenArancelaria = dictamenArancelaria;
        this.fechaDictamen = fechaDictamen;
        this.descripcion = descripcion;
        this.capituloDeclarado = capituloDeclarado;
        this.partidaDeclarada = partidaDeclarada;
        this.incisosDeclarado = incisosDeclarado;
        this.tasaDai = tasaDai;
        this.daiPagado = daiPagado;
        this.ivaPago = ivaPago;
        this.capituloDictaminado = capituloDictaminado;
        this.partidaDictaminado = partidaDictaminado;
        this.incisoDictaminado = incisoDictaminado;
        this.tasaDaiDictaminado = tasaDaiDictaminado;
        this.tipoAlertivo = tipoAlertivo;
        this.opinionDace = opinionDace;
        this.montoTotal = montoTotal;
        this.observaciones = observaciones;
        this.unidadMedida = unidadMedida;
        this.cantidad = cantidad;
        this.valorDeclarado = valorDeclarado;
        this.valorAjustado = valorAjustado;
        this.numeroOrden = numeroOrden;
        this.tratoArancelario = tratoArancelario;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id_solicitud", unique = true, nullable = false)
    public int getIdSolicitud() {
        return this.idSolicitud;
    }

    public void setIdSolicitud(int idSolicitud) {
        this.idSolicitud = idSolicitud;
    }

    @Column(name = "id_agrupacion")
    public Integer getIdAgrupacion() {
        return this.idAgrupacion;
    }

    public void setIdAgrupacion(Integer idAgrupacion) {
        this.idAgrupacion = idAgrupacion;
    }

    @Column(name = "id_estado", nullable = false)
    public int getIdEstado() {
        return this.idEstado;
    }

    public void setIdEstado(int idEstado) {
        this.idEstado = idEstado;
    }

    @Column(name = "no_solicitud", nullable = false)
    public long getNoSolicitud() {
        return this.noSolicitud;
    }

    public void setNoSolicitud(long noSolicitud) {
        this.noSolicitud = noSolicitud;
    }

    @Column(name = "audiencia", length = 50)
    public String getAudiencia() {
        return this.audiencia;
    }

    public void setAudiencia(String audiencia) {
        this.audiencia = audiencia;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "fecha_audiencia", length = 29)
    public Date getFechaAudiencia() {
        return this.fechaAudiencia;
    }

    public void setFechaAudiencia(Date fechaAudiencia) {
        this.fechaAudiencia = fechaAudiencia;
    }

    @Column(name = "nit", length = 11)
    public String getNit() {
        return this.nit;
    }

    public void setNit(String nit) {
        this.nit = nit;
    }

    @Column(name = "nombre", length = 50)
    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    @Column(name = "no_duca", length = 50)
    public String getNoDuca() {
        return this.noDuca;
    }

    public void setNoDuca(String noDuca) {
        this.noDuca = noDuca;
    }

    @Column(name = "no_duca_orden", length = 50)
    public String getNoDucaOrden() {
        return this.noDucaOrden;
    }

    public void setNoDucaOrden(String noDucaOrden) {
        this.noDucaOrden = noDucaOrden;
    }

    
    @Column(name = "fecha_aceptacion", length = 29)
    public String getFechaAceptacion() {
        return this.fechaAceptacion;
    }

    public void setFechaAceptacion(String fechaAceptacion) {
        this.fechaAceptacion = fechaAceptacion;
    }

    @Column(name = "regimen", length = 20)
    public String getRegimen() {
        return this.regimen;
    }

    public void setRegimen(String regimen) {
        this.regimen = regimen;
    }

    @Column(name = "selectivo", length = 20)
    public String getSelectivo() {
        return this.selectivo;
    }

    public void setSelectivo(String selectivo) {
        this.selectivo = selectivo;
    }

    @Column(name = "pais_proveedor", length = 100)
    public String getPaisProveedor() {
        return this.paisProveedor;
    }

    public void setPaisProveedor(String paisProveedor) {
        this.paisProveedor = paisProveedor;
    }

    @Column(name = "tipo_ajuste", length = 50)
    public String getTipoAjuste() {
        return this.tipoAjuste;
    }

    public void setTipoAjuste(String tipoAjuste) {
        this.tipoAjuste = tipoAjuste;
    }

    @Column(name = "expedientes", length = 50)
    public String getExpedientes() {
        return this.expedientes;
    }

    public void setExpedientes(String expedientes) {
        this.expedientes = expedientes;
    }

    @Column(name = "certificado_ensayo", length = 50)
    public String getCertificadoEnsayo() {
        return this.certificadoEnsayo;
    }

    public void setCertificadoEnsayo(String certificadoEnsayo) {
        this.certificadoEnsayo = certificadoEnsayo;
    }

    @Column(name = "dictamen_arancelaria", length = 50)
    public String getDictamenArancelaria() {
        return this.dictamenArancelaria;
    }

    public void setDictamenArancelaria(String dictamenArancelaria) {
        this.dictamenArancelaria = dictamenArancelaria;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "fecha_dictamen", length = 29)
    public Date getFechaDictamen() {
        return this.fechaDictamen;
    }

    public void setFechaDictamen(Date fechaDictamen) {
        this.fechaDictamen = fechaDictamen;
    }

    @Column(name = "descripcion", length = 100)
    public String getDescripcion() {
        return this.descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    @Column(name = "capitulo_declarado")
    public Integer getCapituloDeclarado() {
        return this.capituloDeclarado;
    }

    public void setCapituloDeclarado(Integer capituloDeclarado) {
        this.capituloDeclarado = capituloDeclarado;
    }

    @Column(name = "partida_declarada")
    public Integer getPartidaDeclarada() {
        return this.partidaDeclarada;
    }

    public void setPartidaDeclarada(Integer partidaDeclarada) {
        this.partidaDeclarada = partidaDeclarada;
    }

    @Column(name = "incisos_declarado")
    public Integer getIncisosDeclarado() {
        return this.incisosDeclarado;
    }

    public void setIncisosDeclarado(Integer incisosDeclarado) {
        this.incisosDeclarado = incisosDeclarado;
    }

    @Column(name = "tasa_dai", precision = 17, scale = 17)
    public Double getTasaDai() {
        return this.tasaDai;
    }

    public void setTasaDai(Double tasaDai) {
        this.tasaDai = tasaDai;
    }

    @Column(name = "dai_pagado", precision = 17, scale = 17)
    public Double getDaiPagado() {
        return this.daiPagado;
    }

    public void setDaiPagado(Double daiPagado) {
        this.daiPagado = daiPagado;
    }

    @Column(name = "iva_pago", precision = 17, scale = 17)
    public Double getIvaPago() {
        return this.ivaPago;
    }

    public void setIvaPago(Double ivaPago) {
        this.ivaPago = ivaPago;
    }

    @Column(name = "capitulo_dictaminado")
    public Integer getCapituloDictaminado() {
        return this.capituloDictaminado;
    }

    public void setCapituloDictaminado(Integer capituloDictaminado) {
        this.capituloDictaminado = capituloDictaminado;
    }

    @Column(name = "partida_dictaminado")
    public Integer getPartidaDictaminado() {
        return this.partidaDictaminado;
    }

    public void setPartidaDictaminado(Integer partidaDictaminado) {
        this.partidaDictaminado = partidaDictaminado;
    }

    @Column(name = "inciso_dictaminado")
    public Integer getIncisoDictaminado() {
        return this.incisoDictaminado;
    }

    public void setIncisoDictaminado(Integer incisoDictaminado) {
        this.incisoDictaminado = incisoDictaminado;
    }

    @Column(name = "tasa_dai_dictaminado", precision = 17, scale = 17)
    public Double getTasaDaiDictaminado() {
        return this.tasaDaiDictaminado;
    }

    public void setTasaDaiDictaminado(Double tasaDaiDictaminado) {
        this.tasaDaiDictaminado = tasaDaiDictaminado;
    }

    @Column(name = "tipo_alertivo", length = 30)
    public String getTipoAlertivo() {
        return this.tipoAlertivo;
    }

    public void setTipoAlertivo(String tipoAlertivo) {
        this.tipoAlertivo = tipoAlertivo;
    }

    @Column(name = "opinion_dace", length = 50)
    public String getOpinionDace() {
        return this.opinionDace;
    }

    public void setOpinionDace(String opinionDace) {
        this.opinionDace = opinionDace;
    }

    @Column(name = "monto_total", precision = 17, scale = 17)
    public Double getMontoTotal() {
        return this.montoTotal;
    }

    public void setMontoTotal(Double montoTotal) {
        this.montoTotal = montoTotal;
    }

    @Column(name = "observaciones", length = 100)
    public String getObservaciones() {
        return this.observaciones;
    }

    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }

    @Column(name = "unidad_medida", length = 50)
    public String getUnidadMedida() {
        return this.unidadMedida;
    }

    public void setUnidadMedida(String unidadMedida) {
        this.unidadMedida = unidadMedida;
    }

    @Column(name = "cantidad")
    public Integer getCantidad() {
        return this.cantidad;
    }

    public void setCantidad(Integer cantidad) {
        this.cantidad = cantidad;
    }

    @Column(name = "valor_declarado", precision = 17, scale = 17)
    public Double getValorDeclarado() {
        return this.valorDeclarado;
    }

    public void setValorDeclarado(Double valorDeclarado) {
        this.valorDeclarado = valorDeclarado;
    }

    @Column(name = "valor_ajustado")
    public Double getValorAjustado() {
        return this.valorAjustado;
    }

    public void setValorAjustado(Double valorAjustado) {
        this.valorAjustado = valorAjustado;
    }

    @Column(name = "numero_orden", length = 50)
    public String getNumeroOrden() {
        return this.numeroOrden;
    }

    public void setNumeroOrden(String numeroOrden) {
        this.numeroOrden = numeroOrden;
    }

    @Column(name = "trato_arancelario", length = 8)
    public String getTratoArancelario() {
        return this.tratoArancelario;
    }

    public void setTratoArancelario(String tratoArancelario) {
        this.tratoArancelario = tratoArancelario;
    }

}
