package gt.gob.sat.sat_ifi_sipf.models;
// Generated 21/03/2022 09:26:30 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SipfPerfilUrlId generated by hbm2java
 */
@Embeddable
public class SipfPerfilUrlId  implements java.io.Serializable {


     private int idPerfil;
     private int idUrl;

    public SipfPerfilUrlId() {
    }

    public SipfPerfilUrlId(int idPerfil, int idUrl) {
       this.idPerfil = idPerfil;
       this.idUrl = idUrl;
    }
   


    @Column(name="id_perfil", nullable=false)
    public int getIdPerfil() {
        return this.idPerfil;
    }
    
    public void setIdPerfil(int idPerfil) {
        this.idPerfil = idPerfil;
    }


    @Column(name="id_url", nullable=false)
    public int getIdUrl() {
        return this.idUrl;
    }
    
    public void setIdUrl(int idUrl) {
        this.idUrl = idUrl;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SipfPerfilUrlId) ) return false;
		 SipfPerfilUrlId castOther = ( SipfPerfilUrlId ) other; 
         
		 return (this.getIdPerfil()==castOther.getIdPerfil())
 && (this.getIdUrl()==castOther.getIdUrl());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdPerfil();
         result = 37 * result + this.getIdUrl();
         return result;
   }   


}


