package gt.gob.sat.sat_ifi_sipf.models;
// Generated 21/03/2022 09:25:01 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * SipfFuncion generated by hbm2java
 */
@Entity
@Table(name="sipf_funcion"
    ,schema="sat_ifi_sipf"
)
public class SipfFuncion  implements java.io.Serializable {


     private int idFuncion;
     private String nombreFuncion;

    public SipfFuncion() {
    }

    public SipfFuncion(int idFuncion, String nombreFuncion) {
       this.idFuncion = idFuncion;
       this.nombreFuncion = nombreFuncion;
    }
   
     @Id 

    
    @Column(name="id_funcion", unique=true, nullable=false)
    public int getIdFuncion() {
        return this.idFuncion;
    }
    
    public void setIdFuncion(int idFuncion) {
        this.idFuncion = idFuncion;
    }

    
    @Column(name="nombre_funcion", nullable=false, length=200)
    public String getNombreFuncion() {
        return this.nombreFuncion;
    }
    
    public void setNombreFuncion(String nombreFuncion) {
        this.nombreFuncion = nombreFuncion;
    }




}


