package gt.gob.sat.sat_ifi_sipf.models;
// Generated 1/02/2022 09:33:14 AM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import lombok.Builder;

/**
 * SipfHistoricoOperaciones generated by hbm2java
 */
@Builder
@Entity
@Table(name = "sipf_historico_operaciones",
        schema = "sat_ifi_sipf"
)
public class SipfHistoricoOperaciones implements java.io.Serializable {

    private int idHistoricoOperacion;
    private String nombreTabla;
    private String idCambioRegistro;
    private String usuarioModifica;
    private String ipModifica;
    private int idTipoOperacion;
    private Date fechaModifica;
    private String data;

    public SipfHistoricoOperaciones() {
    }

    public SipfHistoricoOperaciones(int idHistoricoOperacion, String nombreTabla, String idCambioRegistro, String usuarioModifica, String ipModifica, int idTipoOperacion, Date fechaModifica, String data) {
        this.idHistoricoOperacion = idHistoricoOperacion;
        this.nombreTabla = nombreTabla;
        this.idCambioRegistro = idCambioRegistro;
        this.usuarioModifica = usuarioModifica;
        this.ipModifica = ipModifica;
        this.idTipoOperacion = idTipoOperacion;
        this.fechaModifica = fechaModifica;
        this.data = data;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id_historico_operacion", unique = true, nullable = false)
    
    public int getIdHistoricoOperacion() {
        return this.idHistoricoOperacion;
    }

    public void setIdHistoricoOperacion(int idHistoricoOperacion) {
        this.idHistoricoOperacion = idHistoricoOperacion;
    }

    @Column(name = "nombre_tabla", nullable = false, length = 50)
    public String getNombreTabla() {
        return this.nombreTabla;
    }

    public void setNombreTabla(String nombreTabla) {
        this.nombreTabla = nombreTabla;
    }

    @Column(name = "id_cambio_registro", nullable = false, length = 50)
    public String getIdCambioRegistro() {
        return this.idCambioRegistro;
    }

    public void setIdCambioRegistro(String idCambioRegistro) {
        this.idCambioRegistro = idCambioRegistro;
    }

    @Column(name = "usuario_modifica", nullable = false, length = 20)
    public String getUsuarioModifica() {
        return this.usuarioModifica;
    }

    public void setUsuarioModifica(String usuarioModifica) {
        this.usuarioModifica = usuarioModifica;
    }

    @Column(name = "ip_modifica", nullable = false, length = 40)
    public String getIpModifica() {
        return this.ipModifica;
    }

    public void setIpModifica(String ipModifica) {
        this.ipModifica = ipModifica;
    }

    @Column(name = "id_tipo_operacion", nullable = false)
    public int getIdTipoOperacion() {
        return this.idTipoOperacion;
    }

    public void setIdTipoOperacion(int idTipoOperacion) {
        this.idTipoOperacion = idTipoOperacion;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "fecha_modifica", nullable = false, length = 29)
    public Date getFechaModifica() {
        return this.fechaModifica;
    }

    public void setFechaModifica(Date fechaModifica) {
        this.fechaModifica = fechaModifica;
    }

    @Column(name = "data", nullable = false)
    public String getData() {
        return data;
    }

    public void setData(String data) {
        this.data = data;
    }
}
