package gt.gob.sat.sat_ifi_sipf.models;
// Generated 21-sep-2022 9:15:29 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import lombok.Builder;
/**
 * SipfAlcance generated by hbm2java
 */
@Entity
@Builder
@Table(name="sipf_alcance"
    ,schema="sat_ifi_sipf"
)
public class SipfAlcance  implements java.io.Serializable {


     private int idAlcance;
     private int idTipoAlcance;
     private int idEstado;
     private String usuarioModifica;
     private Date fechaModifica;
     private String ipModifica;

    public SipfAlcance() {
    }

	
    public SipfAlcance(int idAlcance, int idTipoAlcance, int idEstado) {
        this.idAlcance = idAlcance;
        this.idTipoAlcance = idTipoAlcance;
        this.idEstado = idEstado;
    }
    public SipfAlcance(int idAlcance, int idTipoAlcance, int idEstado, String usuarioModifica, Date fechaModifica, String ipModifica) {
       this.idAlcance = idAlcance;
       this.idTipoAlcance = idTipoAlcance;
       this.idEstado = idEstado;
       this.usuarioModifica = usuarioModifica;
       this.fechaModifica = fechaModifica;
       this.ipModifica = ipModifica;
    }
   
     @Id 

    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name="id_alcance", unique=true, nullable=false)
    public int getIdAlcance() {
        return this.idAlcance;
    }
    
    public void setIdAlcance(int idAlcance) {
        this.idAlcance = idAlcance;
    }

    
    @Column(name="id_tipo_alcance", nullable=false)
    public int getIdTipoAlcance() {
        return this.idTipoAlcance;
    }
    
    public void setIdTipoAlcance(int idTipoAlcance) {
        this.idTipoAlcance = idTipoAlcance;
    }

    
    @Column(name="id_estado", nullable=false)
    public int getIdEstado() {
        return this.idEstado;
    }
    
    public void setIdEstado(int idEstado) {
        this.idEstado = idEstado;
    }

    
    @Column(name="usuario_modifica", length=50)
    public String getUsuarioModifica() {
        return this.usuarioModifica;
    }
    
    public void setUsuarioModifica(String usuarioModifica) {
        this.usuarioModifica = usuarioModifica;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecha_modifica", length=22)
    public Date getFechaModifica() {
        return this.fechaModifica;
    }
    
    public void setFechaModifica(Date fechaModifica) {
        this.fechaModifica = fechaModifica;
    }

    
    @Column(name="ip_modifica")
    public String getIpModifica() {
        return this.ipModifica;
    }
    
    public void setIpModifica(String ipModifica) {
        this.ipModifica = ipModifica;
    }




}


