package gt.gob.sat.sat_ifi_sipf.models;
// Generated 22/08/2022 03:05:10 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SipfDenunciaColaborador generated by hbm2java
 */
@Entity
@Table(name="sipf_denuncia_colaborador"
    ,schema="sat_ifi_sipf"
)
public class SipfDenunciaColaborador  implements java.io.Serializable {


     private SipfDenunciaColaboradorId id;
     private String usuarioModifica;
     private Date fechaModifica;
     private String ipModifica;

    public SipfDenunciaColaborador() {
    }

	
    public SipfDenunciaColaborador(SipfDenunciaColaboradorId id) {
        this.id = id;
    }
    public SipfDenunciaColaborador(SipfDenunciaColaboradorId id, String usuarioModifica, Date fechaModifica, String ipModifica) {
       this.id = id;
       this.usuarioModifica = usuarioModifica;
       this.fechaModifica = fechaModifica;
       this.ipModifica = ipModifica;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="correlativoDenuncia", column=@Column(name="correlativo_denuncia", nullable=false, length=20) ), 
        @AttributeOverride(name="nitResponsable", column=@Column(name="nit_responsable", nullable=false, length=16) ) } )
    public SipfDenunciaColaboradorId getId() {
        return this.id;
    }
    
    public void setId(SipfDenunciaColaboradorId id) {
        this.id = id;
    }

    
    @Column(name="usuario_modifica", length=16)
    public String getUsuarioModifica() {
        return this.usuarioModifica;
    }
    
    public void setUsuarioModifica(String usuarioModifica) {
        this.usuarioModifica = usuarioModifica;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecha_modifica", length=29)
    public Date getFechaModifica() {
        return this.fechaModifica;
    }
    
    public void setFechaModifica(Date fechaModifica) {
        this.fechaModifica = fechaModifica;
    }

    
    @Column(name="ip_modifica", length=20)
    public String getIpModifica() {
        return this.ipModifica;
    }
    
    public void setIpModifica(String ipModifica) {
        this.ipModifica = ipModifica;
    }




}


