package gt.gob.sat.sat_ifi_sipf.models;
// Generated 8/09/2022 10:25:54 AM by Hibernate Tools 4.3.1

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SipfDenunciaGrabada generated by hbm2java
 */
@Entity
@Table(name = "sipf_denuncia_grabada",
        schema = "sat_ifi_sipf"
)
public class SipfDenunciaGrabada implements java.io.Serializable {

    @JsonProperty(value = "correlativo")
    private String correlativo;
    @JsonProperty(value = "nitDenunciante")
    private String nitDenunciante;
    @JsonProperty(value = "nombreDenunciante")
    private String nombreDenunciante;
    @JsonProperty(value = "telefonoDenunciante")
    private String telefonoDenunciante;
    @JsonProperty(value = "email")
    private String email;
    @JsonProperty(value = "nitDenunciado")
    private String nitDenunciado;
    @JsonProperty(value = "nombreDenunciado")
    private String nombreDenunciado;
    @JsonProperty(value = "establecimientoDenunciado")
    private String establecimientoDenunciado;
    @JsonProperty(value = "direccionFiscalDenunciado")
    private String direccionFiscalDenunciado;
    @JsonProperty(value = "direccionEstDenunciado")
    private String direccionEstDenunciado;
    @JsonProperty(value = "telefonoDenunciado")
    private String telefonoDenunciado;
    @JsonProperty(value = "idMotivo")
    private Integer idMotivo;
    @JsonProperty(value = "otroMotivo")
    private String otroMotivo;
    @JsonProperty(value = "formaPago")
    private String formaPago;
    @JsonProperty(value = "fechaCompra")
    @JsonFormat(pattern = "dd/MM/yyyy")
    private Date fechaCompra;
    @JsonProperty(value = "productoServicio")
    private String productoServicio;
    @JsonProperty(value = "valorCompraServicio")
    private Integer valorCompraServicio;
    @JsonProperty(value = "observaciones")
    private String observaciones;
    @JsonProperty(value = "estado")
    private Integer estado;
    @JsonProperty(value = "auditor")
    private String auditor;
    @JsonProperty(value = "razonRechazo")
    private String razonRechazo;
    @JsonProperty(value = "departamento")
    private Integer departamento;
    @JsonProperty(value = "municipio")
    private Integer municipio;
    @JsonProperty(value = "fechaGrabacion")
    @JsonFormat(pattern = "dd/MM/yyyy")
    private Date fechaGrabacion;
    @JsonProperty(value = "justificacion")
    private String justificacion;
    @JsonProperty(value = "fechaAsignacion")
    @JsonFormat(pattern = "dd/MM/yyyy")
    private Date fechaAsignacion;
    @JsonProperty(value = "fechaAsignacionJs")
    @JsonFormat(pattern = "dd/MM/yyyy")
    private Date fechaAsignacionJs;
    @JsonProperty(value = "fechaCargaPlan")
    @JsonFormat(pattern = "dd/MM/yyyy")
    private Date fechaCargaPlan;
    @JsonProperty(value = "fechaRechazo")
    @JsonFormat(pattern = "dd/MM/yyyy")
    private Date fechaRechazo;
    @JsonProperty(value = "linea")
    private Integer linea;
    @JsonProperty(value = "nitAp")
    private String nitAp;
    @JsonProperty(value = "nitAuditorRechazo")
    private String nitAuditorRechazo;
    @JsonProperty(value = "nitJs")
    private String nitJs;
    @JsonProperty(value = "nitSn")
    private String nitSn;
    @JsonProperty(value = "nombrePlan")
    private String nombrePlan;
    @JsonProperty(value = "region")
    private Integer region;
    @JsonProperty(value = "urlImagen")
    private String urlImagen;
    @JsonProperty(value = "latitud")
    private String latitud;
    @JsonProperty(value = "longitud")
    private String longitud;
    @JsonProperty(value = "idInsumo")
    private Integer idInsumo;
    @JsonProperty(value = "idProceso")
    private Integer idProceso;
    @JsonProperty(value = "idZona")
    private Integer idZona;
    @JsonProperty(value = "idGrupoHabitacional")
    private Integer idGrupoHabitacional;
    @JsonProperty(value = "nombreColonia")
    private String nombreColonia;
    @JsonProperty(value = "idVialidad")
    private Integer idVialidad;
    @JsonProperty(value = "idSubConceptoDenuncia")
    private Integer idSubConceptoDenuncia;
    @JsonProperty(value = "idAlcance")
    private Integer idAlcance;
    @JsonProperty(value = "idProcesoAlcance")
    private Integer idProcesoAlcance;
    @JsonProperty(value = "correlativoAprobacion")
    private String correlativoAprobacion;
    public SipfDenunciaGrabada() {
    }

    public SipfDenunciaGrabada(String correlativo) {
        this.correlativo = correlativo;
    }

    public SipfDenunciaGrabada(String correlativo, String nitDenunciante, String nombreDenunciante, String telefonoDenunciante, String email, String nitDenunciado, String nombreDenunciado, String establecimientoDenunciado, String direccionFiscalDenunciado, String direccionEstDenunciado, String telefonoDenunciado, Integer idMotivo, String otroMotivo, String formaPago, Date fechaCompra, String productoServicio, Integer valorCompraServicio, String observaciones, Integer estado, String auditor, String razonRechazo, Integer departamento, Integer municipio, Date fechaGrabacion, String justificacion, Date fechaAsignacion, Date fechaAsignacionJs, Date fechaCargaPlan, Date fechaRechazo, Integer linea, String nitAp, String nitAuditorRechazo, String nitJs, String nitSn, String nombrePlan, Integer region, String urlImagen, String latitud, String longitud, Integer idInsumo, Integer idProceso, Integer idZona, Integer idGrupoHabitacional, String nombreColonia, Integer idVialidad, Integer idSubConceptoDenuncia, Integer idAlcance, Integer idProcesoAlcance,String correlativoAprobacion) {
        this.correlativo = correlativo;
        this.nitDenunciante = nitDenunciante;
        this.nombreDenunciante = nombreDenunciante;
        this.telefonoDenunciante = telefonoDenunciante;
        this.email = email;
        this.nitDenunciado = nitDenunciado;
        this.nombreDenunciado = nombreDenunciado;
        this.establecimientoDenunciado = establecimientoDenunciado;
        this.direccionFiscalDenunciado = direccionFiscalDenunciado;
        this.direccionEstDenunciado = direccionEstDenunciado;
        this.telefonoDenunciado = telefonoDenunciado;
        this.idMotivo = idMotivo;
        this.otroMotivo = otroMotivo;
        this.formaPago = formaPago;
        this.fechaCompra = fechaCompra;
        this.productoServicio = productoServicio;
        this.valorCompraServicio = valorCompraServicio;
        this.observaciones = observaciones;
        this.estado = estado;
        this.auditor = auditor;
        this.razonRechazo = razonRechazo;
        this.departamento = departamento;
        this.municipio = municipio;
        this.fechaGrabacion = fechaGrabacion;
        this.justificacion = justificacion;
        this.fechaAsignacion = fechaAsignacion;
        this.fechaAsignacionJs = fechaAsignacionJs;
        this.fechaCargaPlan = fechaCargaPlan;
        this.fechaRechazo = fechaRechazo;
        this.linea = linea;
        this.nitAp = nitAp;
        this.nitAuditorRechazo = nitAuditorRechazo;
        this.nitJs = nitJs;
        this.nitSn = nitSn;
        this.nombrePlan = nombrePlan;
        this.region = region;
        this.urlImagen = urlImagen;
        this.latitud = latitud;
        this.longitud = longitud;
        this.idInsumo = idInsumo;
        this.idProceso = idProceso;
        this.idZona = idZona;
        this.idGrupoHabitacional = idGrupoHabitacional;
        this.nombreColonia = nombreColonia;
        this.idVialidad = idVialidad;
        this.idSubConceptoDenuncia = idSubConceptoDenuncia;
        this.idAlcance = idAlcance;
        this.idProcesoAlcance = idProcesoAlcance;
        this.correlativoAprobacion=correlativoAprobacion;
    }

    @Id

    @Column(name = "correlativo", unique = true, nullable = false, length = 20)
    public String getCorrelativo() {
        return this.correlativo;
    }

    public void setCorrelativo(String correlativo) {
        this.correlativo = correlativo;
    }

    @Column(name = "nit_denunciante", length = 12)
    public String getNitDenunciante() {
        return this.nitDenunciante;
    }

    public void setNitDenunciante(String nitDenunciante) {
        this.nitDenunciante = nitDenunciante;
    }

    @Column(name = "id_proceso_alcance", length = 10)
    public Integer getIdProcesoAlcance() {
        return idProcesoAlcance;
    }

    public void setIdProcesoAlcance(Integer idProcesoAlcance) {
        this.idProcesoAlcance = idProcesoAlcance;
    }
    
    
    
    @Column(name = "nombre_denunciante", length = 250)
    public String getNombreDenunciante() {
        return this.nombreDenunciante;
    }

    public void setNombreDenunciante(String nombreDenunciante) {
        this.nombreDenunciante = nombreDenunciante;
    }

    @Column(name = "telefono_denunciante", length = 20)
    public String getTelefonoDenunciante() {
        return this.telefonoDenunciante;
    }

    public void setTelefonoDenunciante(String telefonoDenunciante) {
        this.telefonoDenunciante = telefonoDenunciante;
    }

    @Column(name = "email", length = 50)
    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    @Column(name = "nit_denunciado", length = 12)
    public String getNitDenunciado() {
        return this.nitDenunciado;
    }

    public void setNitDenunciado(String nitDenunciado) {
        this.nitDenunciado = nitDenunciado;
    }

    @Column(name = "nombre_denunciado", length = 250)
    public String getNombreDenunciado() {
        return this.nombreDenunciado;
    }

    public void setNombreDenunciado(String nombreDenunciado) {
        this.nombreDenunciado = nombreDenunciado;
    }

    @Column(name = "establecimiento_denunciado", length = 250)
    public String getEstablecimientoDenunciado() {
        return this.establecimientoDenunciado;
    }

    public void setEstablecimientoDenunciado(String establecimientoDenunciado) {
        this.establecimientoDenunciado = establecimientoDenunciado;
    }

    @Column(name = "direccion_fiscal_denunciado", length = 250)
    public String getDireccionFiscalDenunciado() {
        return this.direccionFiscalDenunciado;
    }

    public void setDireccionFiscalDenunciado(String direccionFiscalDenunciado) {
        this.direccionFiscalDenunciado = direccionFiscalDenunciado;
    }

    @Column(name = "direccion_est_denunciado", length = 250)
    public String getDireccionEstDenunciado() {
        return this.direccionEstDenunciado;
    }

    public void setDireccionEstDenunciado(String direccionEstDenunciado) {
        this.direccionEstDenunciado = direccionEstDenunciado;
    }

    @Column(name = "telefono_denunciado", length = 20)
    public String getTelefonoDenunciado() {
        return this.telefonoDenunciado;
    }

    public void setTelefonoDenunciado(String telefonoDenunciado) {
        this.telefonoDenunciado = telefonoDenunciado;
    }

    @Column(name = "id_motivo")
    public Integer getIdMotivo() {
        return this.idMotivo;
    }

    public void setIdMotivo(Integer idMotivo) {
        this.idMotivo = idMotivo;
    }

    @Column(name = "otro_motivo", length = 100)
    public String getOtroMotivo() {
        return this.otroMotivo;
    }

    public void setOtroMotivo(String otroMotivo) {
        this.otroMotivo = otroMotivo;
    }

    @Column(name = "forma_pago", length = 100)
    public String getFormaPago() {
        return this.formaPago;
    }

    public void setFormaPago(String formaPago) {
        this.formaPago = formaPago;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "fecha_compra", length = 22)
    public Date getFechaCompra() {
        return this.fechaCompra;
    }

    public void setFechaCompra(Date fechaCompra) {
        this.fechaCompra = fechaCompra;
    }

    @Column(name = "producto_servicio", length = 100)
    public String getProductoServicio() {
        return this.productoServicio;
    }

    public void setProductoServicio(String productoServicio) {
        this.productoServicio = productoServicio;
    }

    @Column(name = "valor_compra_servicio")
    public Integer getValorCompraServicio() {
        return this.valorCompraServicio;
    }

    public void setValorCompraServicio(Integer valorCompraServicio) {
        this.valorCompraServicio = valorCompraServicio;
    }

    @Column(name = "observaciones", length = 4000)
    public String getObservaciones() {
        return this.observaciones;
    }

    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }

    @Column(name = "estado", length = 3)
    public Integer getEstado() {
        return this.estado;
    }

    public void setEstado(Integer estado) {
        this.estado = estado;
    }

    @Column(name = "auditor", length = 20)
    public String getAuditor() {
        return this.auditor;
    }

    public void setAuditor(String auditor) {
        this.auditor = auditor;
    }

    @Column(name = "razon_rechazo", length = 1000)
    public String getRazonRechazo() {
        return this.razonRechazo;
    }

    public void setRazonRechazo(String razonRechazo) {
        this.razonRechazo = razonRechazo;
    }

    @Column(name = "departamento")
    public Integer getDepartamento() {
        return this.departamento;
    }

    public void setDepartamento(Integer departamento) {
        this.departamento = departamento;
    }

    @Column(name = "municipio")
    public Integer getMunicipio() {
        return this.municipio;
    }

    public void setMunicipio(Integer municipio) {
        this.municipio = municipio;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "fecha_grabacion", length = 22)
    public Date getFechaGrabacion() {
        return this.fechaGrabacion;
    }

    public void setFechaGrabacion(Date fechaGrabacion) {
        this.fechaGrabacion = fechaGrabacion;
    }

    @Column(name = "justificacion", length = 4000)
    public String getJustificacion() {
        return this.justificacion;
    }

    public void setJustificacion(String justificacion) {
        this.justificacion = justificacion;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "fecha_asignacion", length = 22)
    public Date getFechaAsignacion() {
        return this.fechaAsignacion;
    }

    public void setFechaAsignacion(Date fechaAsignacion) {
        this.fechaAsignacion = fechaAsignacion;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "fecha_asignacion_js", length = 22)
    public Date getFechaAsignacionJs() {
        return this.fechaAsignacionJs;
    }

    public void setFechaAsignacionJs(Date fechaAsignacionJs) {
        this.fechaAsignacionJs = fechaAsignacionJs;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "fecha_carga_plan", length = 22)
    public Date getFechaCargaPlan() {
        return this.fechaCargaPlan;
    }

    public void setFechaCargaPlan(Date fechaCargaPlan) {
        this.fechaCargaPlan = fechaCargaPlan;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "fecha_rechazo", length = 22)
    public Date getFechaRechazo() {
        return this.fechaRechazo;
    }

    public void setFechaRechazo(Date fechaRechazo) {
        this.fechaRechazo = fechaRechazo;
    }

    @Column(name = "linea")
    public Integer getLinea() {
        return this.linea;
    }

    public void setLinea(Integer linea) {
        this.linea = linea;
    }

    @Column(name = "nit_ap", length = 12)
    public String getNitAp() {
        return this.nitAp;
    }

    public void setNitAp(String nitAp) {
        this.nitAp = nitAp;
    }

    @Column(name = "nit_auditor_rechazo", length = 12)
    public String getNitAuditorRechazo() {
        return this.nitAuditorRechazo;
    }

    public void setNitAuditorRechazo(String nitAuditorRechazo) {
        this.nitAuditorRechazo = nitAuditorRechazo;
    }

    @Column(name = "nit_js", length = 12)
    public String getNitJs() {
        return this.nitJs;
    }

    public void setNitJs(String nitJs) {
        this.nitJs = nitJs;
    }

    @Column(name = "nit_sn", length = 12)
    public String getNitSn() {
        return this.nitSn;
    }

    public void setNitSn(String nitSn) {
        this.nitSn = nitSn;
    }

    @Column(name = "nombre_plan", length = 50)
    public String getNombrePlan() {
        return this.nombrePlan;
    }

    public void setNombrePlan(String nombrePlan) {
        this.nombrePlan = nombrePlan;
    }

    @Column(name = "region")
    public Integer getRegion() {
        return this.region;
    }

    public void setRegion(Integer region) {
        this.region = region;
    }

    @Column(name = "url_imagen", length = 150)
    public String getUrlImagen() {
        return this.urlImagen;
    }

    public void setUrlImagen(String urlImagen) {
        this.urlImagen = urlImagen;
    }

    @Column(name = "latitud", length = 20)
    public String getLatitud() {
        return this.latitud;
    }

    public void setLatitud(String latitud) {
        this.latitud = latitud;
    }

    @Column(name = "longitud", length = 20)
    public String getLongitud() {
        return this.longitud;
    }

    public void setLongitud(String longitud) {
        this.longitud = longitud;
    }

    @Column(name = "id_insumo")
    public Integer getIdInsumo() {
        return this.idInsumo;
    }

    public void setIdInsumo(Integer idInsumo) {
        this.idInsumo = idInsumo;
    }

    @Column(name = "id_proceso")
    public Integer getIdProceso() {
        return this.idProceso;
    }

    public void setIdProceso(Integer idProceso) {
        this.idProceso = idProceso;
    }

    @Column(name = "id_zona")
    public Integer getIdZona() {
        return this.idZona;
    }

    public void setIdZona(Integer idZona) {
        this.idZona = idZona;
    }

    @Column(name = "id_grupo_habitacional")
    public Integer getIdGrupoHabitacional() {
        return this.idGrupoHabitacional;
    }

    public void setIdGrupoHabitacional(Integer idGrupoHabitacional) {
        this.idGrupoHabitacional = idGrupoHabitacional;
    }

    @Column(name = "nombre_colonia")
    public String getNombreColonia() {
        return this.nombreColonia;
    }

    public void setNombreColonia(String nombreColonia) {
        this.nombreColonia = nombreColonia;
    }

    @Column(name = "id_vialidad")
    public Integer getIdVialidad() {
        return this.idVialidad;
    }

    public void setIdVialidad(Integer idVialidad) {
        this.idVialidad = idVialidad;
    }

    /**
     * @return the idSubConceptoDenuncia
     */
    @Column(name = "id_sub_concepto_denuncia")
    public Integer getIdSubConceptoDenuncia() {
        return idSubConceptoDenuncia;
    }

    /**
     * @param idSubConceptoDenuncia the idSubConceptoDenuncia to set
     */
    public void setIdSubConceptoDenuncia(Integer idSubConceptoDenuncia) {
        this.idSubConceptoDenuncia = idSubConceptoDenuncia;
    }

    @Column(name = "id_alcance")
    public Integer getIdAlcance() {
        return idAlcance;
    }

    public void setIdAlcance(Integer idAlcance) {
        this.idAlcance = idAlcance;
    }

    /**
     * @return the correlativoAprobacion
     */
     @Column(name = "correlativo_aprobacion")
    public String getCorrelativoAprobacion() {
        return correlativoAprobacion;
    }

    /**
     * @param correlativoAprobacion the correlativoAprobacion to set
     */
    public void setCorrelativoAprobacion(String correlativoAprobacion) {
        this.correlativoAprobacion = correlativoAprobacion;
    }

}
