package gt.gob.sat.sat_ifi_sipf.models;
// Generated Sep 19, 2022 10:43:06 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SipfImpuestoCaso generated by hbm2java
 */
@Entity
@Table(name="sipf_impuesto_caso"
    ,schema="sat_ifi_sipf"
)
public class SipfImpuestoCaso  implements java.io.Serializable {


     private SipfImpuestoCasoId id;
     private String usuarioModifica;
     private Date fechaModifica;
     private String ipModifica;

    public SipfImpuestoCaso() {
    }

    public SipfImpuestoCaso(SipfImpuestoCasoId id, String usuarioModifica, Date fechaModifica, String ipModifica) {
       this.id = id;
       this.usuarioModifica = usuarioModifica;
       this.fechaModifica = fechaModifica;
       this.ipModifica = ipModifica;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idCaso", column=@Column(name="id_caso", nullable=false) ), 
        @AttributeOverride(name="idImpuesto", column=@Column(name="id_impuesto", nullable=false) ) } )
    public SipfImpuestoCasoId getId() {
        return this.id;
    }
    
    public void setId(SipfImpuestoCasoId id) {
        this.id = id;
    }

    
    @Column(name="usuario_modifica", nullable=false, length=20)
    public String getUsuarioModifica() {
        return this.usuarioModifica;
    }
    
    public void setUsuarioModifica(String usuarioModifica) {
        this.usuarioModifica = usuarioModifica;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecha_modifica", nullable=false, length=29)
    public Date getFechaModifica() {
        return this.fechaModifica;
    }
    
    public void setFechaModifica(Date fechaModifica) {
        this.fechaModifica = fechaModifica;
    }

    
    @Column(name="ip_modifica", nullable=false, length=40)
    public String getIpModifica() {
        return this.ipModifica;
    }
    
    public void setIpModifica(String ipModifica) {
        this.ipModifica = ipModifica;
    }




}


