package gt.gob.sat.sat_ifi_sipf.models;
// Generated 1/02/2022 09:23:59 AM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import lombok.Builder;

/**
 * SipfCasosMasivos generated by hbm2java
 */
@Entity
@Builder
@Table(name = "sipf_casos_masivos",
        schema = "sat_ifi_sipf"
)
public class SipfCasosMasivos implements java.io.Serializable {

    private int idCaso;
    private String objetivoCasoMasiva;
    private Integer idTipoAlcance;
    private String territorioMasivo;
    private Integer idVersionAlcance;

    public SipfCasosMasivos() {
    }

    public SipfCasosMasivos(int idCaso, String objetivoCasoMasiva) {
        this.idCaso = idCaso;
        this.objetivoCasoMasiva = objetivoCasoMasiva;
    }

    public SipfCasosMasivos(int idCaso, String objetivoCasoMasiva, Integer idTipoAlcance, String territorioMasivo, Integer idVersionAlcance) {
        this.idCaso = idCaso;
        this.objetivoCasoMasiva = objetivoCasoMasiva;
        this.idTipoAlcance = idTipoAlcance;
        this.territorioMasivo = territorioMasivo;
        this.idVersionAlcance = idVersionAlcance;
    }

    @Id
    @Column(name = "id_caso", unique = true, nullable = false)
    public int getIdCaso() {
        return this.idCaso;
    }

    public void setIdCaso(int idCaso) {
        this.idCaso = idCaso;
    }

    @Column(name = "objetivo_caso_masiva", nullable = false, length = 400)
    public String getObjetivoCasoMasiva() {
        return this.objetivoCasoMasiva;
    }

    public void setObjetivoCasoMasiva(String objetivoCasoMasiva) {
        this.objetivoCasoMasiva = objetivoCasoMasiva;
    }

    @Column(name = "id_tipo_alcance")
    public Integer getIdTipoAlcance() {
        return this.idTipoAlcance;
    }

    public void setIdTipoAlcance(Integer idTipoAlcance) {
        this.idTipoAlcance = idTipoAlcance;
    }

    @Column(name = "territorio_masivo", length = 500)
    public String getTerritorioMasivo() {
        return this.territorioMasivo;
    }

    public void setTerritorioMasivo(String territorioMasivo) {
        this.territorioMasivo = territorioMasivo;
    }

    @Column(name = "id_version_alcance")
    public Integer getIdVersionAlcance() {
        return this.idVersionAlcance;
    }

    public void setIdVersionAlcance(Integer idVersionAlcance) {
        this.idVersionAlcance = idVersionAlcance;
    }

}
