package gt.gob.sat.sat_ifi_sipf.models;
// Generated 21/03/2022 09:25:01 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * SipfUrl generated by hbm2java
 */
@Entity
@Table(name="sipf_url"
    ,schema="sat_ifi_sipf"
)
public class SipfUrl  implements java.io.Serializable {


     private int idUrl;
     private String url;
     private String metodo;

    public SipfUrl() {
    }

    public SipfUrl(int idUrl, String url, String metodo) {
       this.idUrl = idUrl;
       this.url = url;
       this.metodo = metodo;
    }
   
     @Id 

    
    @Column(name="id_url", unique=true, nullable=false)
    public int getIdUrl() {
        return this.idUrl;
    }
    
    public void setIdUrl(int idUrl) {
        this.idUrl = idUrl;
    }

    
    @Column(name="url", nullable=false, length=400)
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }

    
    @Column(name="metodo", nullable=false, length=200)
    public String getMetodo() {
        return this.metodo;
    }
    
    public void setMetodo(String metodo) {
        this.metodo = metodo;
    }




}


