package gt.gob.sat.sat_ifi_sipf.models;
// Generated 1/02/2022 09:30:27 AM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.Max;
import javax.validation.constraints.Min;
import javax.validation.constraints.NotEmpty;
import lombok.Builder;

/**
 * SipfHallazgosEncontrados generated by hbm2java
 */
@Entity
@Builder
@Table(name = "sipf_hallazgos_encontrados",
        schema = "sat_ifi_sipf"
)
public class SipfHallazgosEncontrados implements java.io.Serializable {

    private int idHallazgo;
    private String nombre;
    private String descripcion;
    private int idCaso;

    public SipfHallazgosEncontrados() {
    }

    public SipfHallazgosEncontrados(int idHallazgo, String nombre, String descripcion, int idCaso) {
        this.idHallazgo = idHallazgo;
        this.nombre = nombre;
        this.descripcion = descripcion;
        this.idCaso = idCaso;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id_hallazgo", unique = true, nullable = false)
    public int getIdHallazgo() {
        return this.idHallazgo;
    }

    public void setIdHallazgo(int idHallazgo) {
        this.idHallazgo = idHallazgo;
    }

    @Column(name = "nombre", nullable = false, length = 300)
    public String getNombre() {
        return nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    @Column(name = "descripcion", nullable = false)
    public String getDescripcion() {
        return this.descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    @Column(name = "id_caso", nullable = false)
    public int getIdCaso() {
        return this.idCaso;
    }

    public void setIdCaso(int idCaso) {
        this.idCaso = idCaso;
    }
}
