package gt.gob.sat.sat_ifi_sipf.models;
// Generated 1/02/2022 09:22:58 AM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SipfAlcancesMasivosVersiones generated by hbm2java
 */
@Entity
@Table(name = "sipf_alcances_masivos_versiones",
        schema = "sat_ifi_sipf"
)
public class SipfAlcancesMasivosVersiones implements java.io.Serializable {

    private SipfAlcancesMasivosVersionesId id;
    private Date fechaModifica;
    private int idEstado;
    private String ipModifica;
    private String justificacion;
    private String objetivo;
    private String procedimientosEspecificos;
    private String usuarioModifica;
    private String actividad;

    public SipfAlcancesMasivosVersiones() {
    }

    public SipfAlcancesMasivosVersiones(SipfAlcancesMasivosVersionesId id, Date fechaModifica, int idEstado, String ipModifica, String justificacion, String objetivo, String procedimientosEspecificos, String usuarioModifica, String actividad) {
        this.id = id;
        this.fechaModifica = fechaModifica;
        this.idEstado = idEstado;
        this.ipModifica = ipModifica;
        this.justificacion = justificacion;
        this.objetivo = objetivo;
        this.procedimientosEspecificos = procedimientosEspecificos;
        this.usuarioModifica = usuarioModifica;
        this.actividad = actividad;
    }

    @EmbeddedId

    @AttributeOverrides({
        @AttributeOverride(name = "idTipoAlcanceMasivo", column = @Column(name = "id_tipo_alcance_masivo", nullable = false))
        , 
        @AttributeOverride(name = "version", column = @Column(name = "version", nullable = false))})
    public SipfAlcancesMasivosVersionesId getId() {
        return this.id;
    }

    public void setId(SipfAlcancesMasivosVersionesId id) {
        this.id = id;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "fecha_modifica", nullable = false, length = 22)
    public Date getFechaModifica() {
        return this.fechaModifica;
    }

    public void setFechaModifica(Date fechaModifica) {
        this.fechaModifica = fechaModifica;
    }

    @Column(name = "id_estado", nullable = false)
    public int getIdEstado() {
        return this.idEstado;
    }

    public void setIdEstado(int idEstado) {
        this.idEstado = idEstado;
    }

    @Column(name = "ip_modifica", nullable = false, length = 40)
    public String getIpModifica() {
        return this.ipModifica;
    }

    public void setIpModifica(String ipModifica) {
        this.ipModifica = ipModifica;
    }

    @Column(name = "justificacion", nullable = false, length = 500)
    public String getJustificacion() {
        return this.justificacion;
    }

    public void setJustificacion(String justificacion) {
        this.justificacion = justificacion;
    }

    @Column(name = "objetivo", nullable = false, length = 500)
    public String getObjetivo() {
        return this.objetivo;
    }

    public void setObjetivo(String objetivo) {
        this.objetivo = objetivo;
    }

    @Column(name = "procedimientos_especificos", nullable = false, length = 1000)
    public String getProcedimientosEspecificos() {
        return this.procedimientosEspecificos;
    }

    public void setProcedimientosEspecificos(String procedimientosEspecificos) {
        this.procedimientosEspecificos = procedimientosEspecificos;
    }

    @Column(name = "usuario_modifica", nullable = false, length = 20)
    public String getUsuarioModifica() {
        return this.usuarioModifica;
    }

    public void setUsuarioModifica(String usuarioModifica) {
        this.usuarioModifica = usuarioModifica;
    }

    @Column(name = "actividad", nullable = false, length = 500)
    public String getActividad() {
        return actividad;
    }

    public void setActividad(String actividad) {
        this.actividad = actividad;
    }
}
