package gt.gob.sat.sat_ifi_sipf.models;
// Generated 1/02/2022 09:27:48 AM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import lombok.Builder;

/**
 * SipfColaborador generated by hbm2java
 */
@Entity
@Builder
@Table(name = "sipf_colaborador",
        schema = "sat_ifi_sipf"
)
public class SipfColaborador implements java.io.Serializable {

    private String nit;
    private String puestoTrabajo;
    private long idEstado;
    private String login;
    private String nombres;
    private long idGerencia;
    private String correo;
    private String usuarioModifica;
    private Date fechaModifica;
    private String ipModifica;

    public SipfColaborador() {
    }

    public SipfColaborador(String nit, String puestoTrabajo, long idEstado, String login, String nombres, long idGerencia, String correo, String usuarioModifica, Date fechaModifica, String ipModifica) {
        this.nit = nit;
        this.puestoTrabajo = puestoTrabajo;
        this.idEstado = idEstado;
        this.login = login;
        this.nombres = nombres;
        this.idGerencia = idGerencia;
        this.correo = correo;
        this.usuarioModifica = usuarioModifica;
        this.fechaModifica = fechaModifica;
        this.ipModifica = ipModifica;
    }

    
    @Id

    @Column(name = "nit", unique = true, nullable = false, length = 16)
    public String getNit() {
        return this.nit;
    }

    public void setNit(String nit) {
        this.nit = nit;
    }

    @Column(name = "puesto_trabajo", nullable = false)
    public String getPuestoTrabajo() {
        return this.puestoTrabajo;
    }

    public void setPuestoTrabajo(String idPuestoTrabajo) {
        this.puestoTrabajo = idPuestoTrabajo;
    }

    @Column(name = "id_estado", nullable = false)
    public long getIdEstado() {
        return this.idEstado;
    }

    public void setIdEstado(long idEstado) {
        this.idEstado = idEstado;
    }

    @Column(name = "login", nullable = false)
    public String getLogin() {
        return this.login;
    }

    public void setLogin(String login) {
        this.login = login;
    }

    @Column(name = "nombres", nullable = false, length = 200)
    public String getNombres() {
        return this.nombres;
    }

    public void setNombres(String nombres) {
        this.nombres = nombres;
    }

    @Column(name = "id_gerencia", nullable = false)
    public long getIdGerencia() {
        return this.idGerencia;
    }

    public void setIdGerencia(long idGerencia) {
        this.idGerencia = idGerencia;
    }

    @Column(name = "correo", nullable = false, length = 100)
    public String getCorreo() {
        return this.correo;
    }

    public void setCorreo(String correo) {
        this.correo = correo;
    }

    @Column(name = "usuario_modifica", nullable = false, length = 20)
    public String getUsuarioModifica() {
        return this.usuarioModifica;
    }

    public void setUsuarioModifica(String usuarioModifica) {
        this.usuarioModifica = usuarioModifica;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "fecha_modifica", nullable = false, length = 22)
    public Date getFechaModifica() {
        return this.fechaModifica;
    }

    public void setFechaModifica(Date fechaModifica) {
        this.fechaModifica = fechaModifica;
    }

    @Column(name = "ip_modifica", nullable = false, length = 40)
    public String getIpModifica() {
        return this.ipModifica;
    }

    public void setIpModifica(String ipModifica) {
        this.ipModifica = ipModifica;
    }

}
