package gt.gob.sat.sat_ifi_sipf.models;
// Generated 1/02/2022 09:22:58 AM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;
import lombok.Builder;

/**
 * SipfAlcancesMasivosVersionesId generated by hbm2java
 */
@Embeddable
@Builder
public class SipfAlcancesMasivosVersionesId implements java.io.Serializable {

    private int idTipoAlcanceMasivo;
    private int version;

    public SipfAlcancesMasivosVersionesId() {
    }

    public SipfAlcancesMasivosVersionesId(int idTipoAlcanceMasivo, int version) {
        this.idTipoAlcanceMasivo = idTipoAlcanceMasivo;
        this.version = version;
    }

    @Column(name = "id_tipo_alcance_masivo", nullable = false)
    public int getIdTipoAlcanceMasivo() {
        return this.idTipoAlcanceMasivo;
    }

    public void setIdTipoAlcanceMasivo(int idTipoAlcanceMasivo) {
        this.idTipoAlcanceMasivo = idTipoAlcanceMasivo;
    }

    @Column(name = "version", nullable = false)
    public int getVersion() {
        return this.version;
    }

    public void setVersion(int version) {
        this.version = version;
    }

}
