package gt.gob.sat.sat_ifi_sipf.models;
// Generated 16/06/2022 06:51:22 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SipfComentarioHistoricoNombramiento generated by hbm2java
 */
@Entity
@Table(name="sipf_comentario_historico_nombramiento"
    ,schema="sat_ifi_sipf"
)
public class SipfComentarioHistoricoNombramiento  implements java.io.Serializable {


     private SipfComentarioHistoricoNombramientoId id;
     private String comentario;
     private String usuarioModificacion;
     private Date fechaModificacion;
     private String ipModificacion;

    public SipfComentarioHistoricoNombramiento() {
    }

	
    public SipfComentarioHistoricoNombramiento(SipfComentarioHistoricoNombramientoId id) {
        this.id = id;
    }
    public SipfComentarioHistoricoNombramiento(SipfComentarioHistoricoNombramientoId id, String comentario, String usuarioModificacion, Date fechaModificacion, String ipModificacion) {
       this.id = id;
       this.comentario = comentario;
       this.usuarioModificacion = usuarioModificacion;
       this.fechaModificacion = fechaModificacion;
       this.ipModificacion = ipModificacion;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="nombrameinto", column=@Column(name="nombrameinto", nullable=false) ), 
        @AttributeOverride(name="expediente", column=@Column(name="expediente", nullable=false) ) } )
    public SipfComentarioHistoricoNombramientoId getId() {
        return this.id;
    }
    
    public void setId(SipfComentarioHistoricoNombramientoId id) {
        this.id = id;
    }

    
    @Column(name="comentario")
    public String getComentario() {
        return this.comentario;
    }
    
    public void setComentario(String comentario) {
        this.comentario = comentario;
    }

    
    @Column(name="usuario_modificacion")
    public String getUsuarioModificacion() {
        return this.usuarioModificacion;
    }
    
    public void setUsuarioModificacion(String usuarioModificacion) {
        this.usuarioModificacion = usuarioModificacion;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha_modificacion", length=13)
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }

    
    @Column(name="ip_modificacion")
    public String getIpModificacion() {
        return this.ipModificacion;
    }
    
    public void setIpModificacion(String ipModificacion) {
        this.ipModificacion = ipModificacion;
    }




}


