package gt.gob.sat.sat_ifi_sipf.models;
// Generated Aug 19, 2022 10:27:46 AM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import lombok.Builder;

/**
 * SipfCasos generated by hbm2java
 */
@Builder
@Entity
@Table(name = "sipf_casos",
        schema = "sat_ifi_sipf"
)
public class SipfCasos implements java.io.Serializable {

    private int idCaso;
    private int idEstado;
    private Integer idOrigen;
    private Integer idGerencia;
    private String idProceso;
    private Double montoRecaudado;
    private Integer idPrograma;
    private int idDepartamento;
    private String correlativoAprobacion;
    private String usuarioModifica;
    private Date fechaModifica;
    private String ipModifica;
    private Integer idInsumo;
    private Date periodoRevisionInicio;
    private Date periodoRevisionFin;
    private String nitContribuyente;
    private Integer idZona;
    private Integer idMunicipio;

    public SipfCasos() {
    }

    public SipfCasos(int idCaso, int idEstado, int idDepartamento, String usuarioModifica, Date fechaModifica, String ipModifica, String nitContribuyente) {
        this.idCaso = idCaso;
        this.idEstado = idEstado;
        this.idDepartamento = idDepartamento;
        this.usuarioModifica = usuarioModifica;
        this.fechaModifica = fechaModifica;
        this.ipModifica = ipModifica;
        this.nitContribuyente = nitContribuyente;
    }

    public SipfCasos(int idCaso, int idEstado, Integer idOrigen, Integer idGerencia, String idProceso, Double montoRecaudado, Integer idPrograma, int idDepartamento, String correlativoAprobacion, String usuarioModifica, Date fechaModifica, String ipModifica, Integer idInsumo, Date periodoRevisionInicio, Date periodoRevisionFin, String nitContribuyente, Integer idZona, Integer idMunicipio) {
        this.idCaso = idCaso;
        this.idEstado = idEstado;
        this.idOrigen = idOrigen;
        this.idGerencia = idGerencia;
        this.idProceso = idProceso;
        this.montoRecaudado = montoRecaudado;
        this.idPrograma = idPrograma;
        this.idDepartamento = idDepartamento;
        this.correlativoAprobacion = correlativoAprobacion;
        this.usuarioModifica = usuarioModifica;
        this.fechaModifica = fechaModifica;
        this.ipModifica = ipModifica;
        this.idInsumo = idInsumo;
        this.periodoRevisionInicio = periodoRevisionInicio;
        this.periodoRevisionFin = periodoRevisionFin;
        this.nitContribuyente = nitContribuyente;
        this.idZona = idZona;
        this.idMunicipio = idMunicipio;
    }

    @Id

    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id_caso", unique = true, nullable = false)
    public int getIdCaso() {
        return this.idCaso;
    }

    public void setIdCaso(int idCaso) {
        this.idCaso = idCaso;
    }

    @Column(name = "id_estado", nullable = false)
    public int getIdEstado() {
        return this.idEstado;
    }

    public void setIdEstado(int idEstado) {
        this.idEstado = idEstado;
    }

    @Column(name = "id_origen")
    public Integer getIdOrigen() {
        return this.idOrigen;
    }

    public void setIdOrigen(Integer idOrigen) {
        this.idOrigen = idOrigen;
    }

    @Column(name = "id_gerencia")
    public Integer getIdGerencia() {
        return this.idGerencia;
    }

    public void setIdGerencia(Integer idGerencia) {
        this.idGerencia = idGerencia;
    }

    @Column(name = "id_proceso", length = 150)
    public String getIdProceso() {
        return this.idProceso;
    }

    public void setIdProceso(String idProceso) {
        this.idProceso = idProceso;
    }

    @Column(name = "monto_recaudado", precision = 17, scale = 17)
    public Double getMontoRecaudado() {
        return this.montoRecaudado;
    }

    public void setMontoRecaudado(Double montoRecaudado) {
        this.montoRecaudado = montoRecaudado;
    }

    @Column(name = "id_programa")
    public Integer getIdPrograma() {
        return this.idPrograma;
    }

    public void setIdPrograma(Integer idPrograma) {
        this.idPrograma = idPrograma;
    }

    @Column(name = "id_departamento", nullable = false)
    public int getIdDepartamento() {
        return this.idDepartamento;
    }

    public void setIdDepartamento(int idDepartamento) {
        this.idDepartamento = idDepartamento;
    }

    @Column(name = "correlativo_aprobacion", length = 50)
    public String getCorrelativoAprobacion() {
        return this.correlativoAprobacion;
    }

    public void setCorrelativoAprobacion(String correlativoAprobacion) {
        this.correlativoAprobacion = correlativoAprobacion;
    }

    @Column(name = "usuario_modifica", nullable = false, length = 20)
    public String getUsuarioModifica() {
        return this.usuarioModifica;
    }

    public void setUsuarioModifica(String usuarioModifica) {
        this.usuarioModifica = usuarioModifica;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "fecha_modifica", nullable = false, length = 22)
    public Date getFechaModifica() {
        return this.fechaModifica;
    }

    public void setFechaModifica(Date fechaModifica) {
        this.fechaModifica = fechaModifica;
    }

    @Column(name = "ip_modifica", nullable = false, length = 40)
    public String getIpModifica() {
        return this.ipModifica;
    }

    public void setIpModifica(String ipModifica) {
        this.ipModifica = ipModifica;
    }

    @Column(name = "id_insumo")
    public Integer getIdInsumo() {
        return this.idInsumo;
    }

    public void setIdInsumo(Integer idInsumo) {
        this.idInsumo = idInsumo;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "periodo_revision_inicio", length = 22)
    public Date getPeriodoRevisionInicio() {
        return this.periodoRevisionInicio;
    }

    public void setPeriodoRevisionInicio(Date periodoRevisionInicio) {
        this.periodoRevisionInicio = periodoRevisionInicio;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "periodo_revision_fin", length = 22)
    public Date getPeriodoRevisionFin() {
        return this.periodoRevisionFin;
    }

    public void setPeriodoRevisionFin(Date periodoRevisionFin) {
        this.periodoRevisionFin = periodoRevisionFin;
    }

    @Column(name = "nit_contribuyente", nullable = false, length = 15)
    public String getNitContribuyente() {
        return this.nitContribuyente;
    }

    public void setNitContribuyente(String nitContribuyente) {
        this.nitContribuyente = nitContribuyente;
    }

    @Column(name = "id_zona")
    public Integer getIdZona() {
        return this.idZona;
    }

    public void setIdZona(Integer idZona) {
        this.idZona = idZona;
    }

    @Column(name = "id_municipio")
    public Integer getIdMunicipio() {
        return this.idMunicipio;
    }

    public void setIdMunicipio(Integer idMunicipio) {
        this.idMunicipio = idMunicipio;
    }

}
