package gt.gob.sat.sat_ifi_sipf.models;
// Generated 16-nov-2022 14:46:19 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import lombok.Builder;

/**
 * SipfPresenciasFiscales generated by hbm2java
 */
@Entity
@Builder
@Table(name = "sipf_presencias_fiscales",
         schema = "sat_ifi_sipf"
)
public class SipfPresenciasFiscales  implements java.io.Serializable {


     private int idFormulario;
     private Date fechaInicio;
     private Date fechaFin;
     private String lugarDepartamental;
     private Integer idPrograma;
     private int meta;
     private String idProceso;
     private int idEstado;
     private String usuarioModifica;
     private Date fechaModifica;
     private String usuarioCreacion;
     private Integer idAlcance;
     private Integer idGerencia;
     private String correlativoAprobacion;
     private String lugarEjecucion;

    public SipfPresenciasFiscales() {
    }

	
    public SipfPresenciasFiscales(int idFormulario, Date fechaInicio, Date fechaFin, String lugarDepartamental, int meta, int idEstado, String usuarioModifica, Date fechaModifica, String usuarioCreacion) {
        this.idFormulario = idFormulario;
        this.fechaInicio = fechaInicio;
        this.fechaFin = fechaFin;
        this.lugarDepartamental = lugarDepartamental;
        this.meta = meta;
        this.idEstado = idEstado;
        this.usuarioModifica = usuarioModifica;
        this.fechaModifica = fechaModifica;
        this.usuarioCreacion = usuarioCreacion;
    }
    public SipfPresenciasFiscales(int idFormulario, Date fechaInicio, Date fechaFin, String lugarDepartamental, Integer idPrograma, int meta, String idProceso, int idEstado, String usuarioModifica, Date fechaModifica, String usuarioCreacion, Integer idAlcance, Integer idGerencia, String correlativoAprobacion, String lugarEjecucion) {
       this.idFormulario = idFormulario;
       this.fechaInicio = fechaInicio;
       this.fechaFin = fechaFin;
       this.lugarDepartamental = lugarDepartamental;
       this.idPrograma = idPrograma;
       this.meta = meta;
       this.idProceso = idProceso;
       this.idEstado = idEstado;
       this.usuarioModifica = usuarioModifica;
       this.fechaModifica = fechaModifica;
       this.usuarioCreacion = usuarioCreacion;
       this.idAlcance = idAlcance;
       this.idGerencia = idGerencia;
       this.correlativoAprobacion = correlativoAprobacion;
       this.lugarEjecucion = lugarEjecucion;
    }
   
     @Id 
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id_formulario", unique = true, nullable = false)
    public int getIdFormulario() {
        return this.idFormulario;
    }
    
    public void setIdFormulario(int idFormulario) {
        this.idFormulario = idFormulario;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecha_inicio", nullable=false, length=22)
    public Date getFechaInicio() {
        return this.fechaInicio;
    }
    
    public void setFechaInicio(Date fechaInicio) {
        this.fechaInicio = fechaInicio;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecha_fin", nullable=false, length=22)
    public Date getFechaFin() {
        return this.fechaFin;
    }
    
    public void setFechaFin(Date fechaFin) {
        this.fechaFin = fechaFin;
    }

    
    @Column(name="lugar_departamental", nullable=false, length=1000)
    public String getLugarDepartamental() {
        return this.lugarDepartamental;
    }
    
    public void setLugarDepartamental(String lugarDepartamental) {
        this.lugarDepartamental = lugarDepartamental;
    }

    
    @Column(name="id_programa")
    public Integer getIdPrograma() {
        return this.idPrograma;
    }
    
    public void setIdPrograma(Integer idPrograma) {
        this.idPrograma = idPrograma;
    }

    
    @Column(name="meta", nullable=false)
    public int getMeta() {
        return this.meta;
    }
    
    public void setMeta(int meta) {
        this.meta = meta;
    }

    
    @Column(name="id_proceso", length=150)
    public String getIdProceso() {
        return this.idProceso;
    }
    
    public void setIdProceso(String idProceso) {
        this.idProceso = idProceso;
    }

    
    @Column(name="id_estado", nullable=false)
    public int getIdEstado() {
        return this.idEstado;
    }
    
    public void setIdEstado(int idEstado) {
        this.idEstado = idEstado;
    }

    
    @Column(name="usuario_modifica", nullable=false, length=50)
    public String getUsuarioModifica() {
        return this.usuarioModifica;
    }
    
    public void setUsuarioModifica(String usuarioModifica) {
        this.usuarioModifica = usuarioModifica;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecha_modifica", nullable=false, length=22)
    public Date getFechaModifica() {
        return this.fechaModifica;
    }
    
    public void setFechaModifica(Date fechaModifica) {
        this.fechaModifica = fechaModifica;
    }

    
    @Column(name="usuario_creacion", nullable=false, length=50)
    public String getUsuarioCreacion() {
        return this.usuarioCreacion;
    }
    
    public void setUsuarioCreacion(String usuarioCreacion) {
        this.usuarioCreacion = usuarioCreacion;
    }

    
    @Column(name="id_alcance")
    public Integer getIdAlcance() {
        return this.idAlcance;
    }
    
    public void setIdAlcance(Integer idAlcance) {
        this.idAlcance = idAlcance;
    }

    
    @Column(name="id_gerencia")
    public Integer getIdGerencia() {
        return this.idGerencia;
    }
    
    public void setIdGerencia(Integer idGerencia) {
        this.idGerencia = idGerencia;
    }

    
    @Column(name="correlativo_aprobacion")
    public String getCorrelativoAprobacion() {
        return this.correlativoAprobacion;
    }
    
    public void setCorrelativoAprobacion(String correlativoAprobacion) {
        this.correlativoAprobacion = correlativoAprobacion;
    }

    
    @Column(name="lugar_ejecucion")
    public String getLugarEjecucion() {
        return this.lugarEjecucion;
    }
    
    public void setLugarEjecucion(String lugarEjecucion) {
        this.lugarEjecucion = lugarEjecucion;
    }




}


