package gt.gob.sat.sat_ifi_sipf.models;
// Generated 1/02/2022 09:37:01 AM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SipfIntegranteGrupo generated by hbm2java
 */
@Entity
@Table(name = "sipf_integrante_grupo",
        schema = "sat_ifi_sipf"
)
@IdClass(SipfIntegranteGrupoId.class)
public class SipfIntegranteGrupo implements java.io.Serializable {

    private long idGrupo;
    private String nit;
    private String usuarioModifica;
    private Date fechaModifica;
    private String ipModifica;
    private Integer idPerfil;
    private Integer idRol;
    private Integer idEstado;

    public SipfIntegranteGrupo() {
    }

    public SipfIntegranteGrupo(long idGrupo, String nit) {
        this.idGrupo = idGrupo;
        this.nit = nit;
    }

    public SipfIntegranteGrupo(long idGrupo, String nit, String usuarioModifica, Date fechaModifica, String ipModifica, Integer idPerfil, Integer idRol, Integer idEstado) {
        this.idGrupo = idGrupo;
        this.nit = nit;
        this.usuarioModifica = usuarioModifica;
        this.fechaModifica = fechaModifica;
        this.ipModifica = ipModifica;
        this.idPerfil = idPerfil;
        this.idRol = idRol;
        this.idEstado = idEstado;
    }

    @Id
    @Column(name = "id_grupo", nullable = false)
    public long getIdGrupo() {
        return this.idGrupo;
    }

    public void setIdGrupo(long idGrupo) {
        this.idGrupo = idGrupo;
    }

    @Id
    @Column(name = "nit", nullable = false, length = 16)
    public String getNit() {
        return this.nit;
    }

    public void setNit(String nit) {
        this.nit = nit;
    }

    @Column(name = "usuario_modifica", nullable = false, length = 20)
    public String getUsuarioModifica() {
        return this.usuarioModifica;
    }

    public void setUsuarioModifica(String usuarioModifica) {
        this.usuarioModifica = usuarioModifica;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "fecha_modifica", nullable = false, length = 29)
    public Date getFechaModifica() {
        return this.fechaModifica;
    }

    public void setFechaModifica(Date fechaModifica) {
        this.fechaModifica = fechaModifica;
    }

    @Column(name = "ip_modifica", nullable = false, length = 40)
    public String getIpModifica() {
        return this.ipModifica;
    }

    public void setIpModifica(String ipModifica) {
        this.ipModifica = ipModifica;
    }

    @Id
    @Column(name = "id_perfil")
    public Integer getIdPerfil() {
        return idPerfil;
    }

    public void setIdPerfil(Integer idPerfil) {
        this.idPerfil = idPerfil;
    }

    @Column(name = "id_rol")
    public Integer getIdRol() {
        return idRol;
    }

    public void setIdRol(Integer idRol) {
        this.idRol = idRol;
    }

    @Column(name = "id_estado")
    public Integer getIdEstado() {
        return idEstado;
    }

    public void setIdEstado(Integer idEstado) {
        this.idEstado = idEstado;
    }
}
