package gt.gob.sat.sat_ifi_sipf.models;
// Generated 1/02/2022 09:22:58 AM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import lombok.Builder;

/**
 * SipfAlcancesMasivos generated by hbm2java
 */
@Entity
@Builder
@Table(name = "sipf_alcances_masivos",
        schema = "sat_ifi_sipf"
)
public class SipfAlcancesMasivos implements java.io.Serializable {

    private int idAlcanceMasivo;
    private String descripcionAlcance;
    private Date fechaModifica;
    private String ipModifica;
    private String nombreAlcance;
    private String usuarioModifica;

    public SipfAlcancesMasivos() {
    }

    public SipfAlcancesMasivos(int idAlcanceMasivo, Date fechaModifica, String ipModifica, String nombreAlcance, String usuarioModifica) {
        this.idAlcanceMasivo = idAlcanceMasivo;
        this.fechaModifica = fechaModifica;
        this.ipModifica = ipModifica;
        this.nombreAlcance = nombreAlcance;
        this.usuarioModifica = usuarioModifica;
    }

    public SipfAlcancesMasivos(int idAlcanceMasivo, String descripcionAlcance, Date fechaModifica, String ipModifica, String nombreAlcance, String usuarioModifica) {
        this.idAlcanceMasivo = idAlcanceMasivo;
        this.descripcionAlcance = descripcionAlcance;
        this.fechaModifica = fechaModifica;
        this.ipModifica = ipModifica;
        this.nombreAlcance = nombreAlcance;
        this.usuarioModifica = usuarioModifica;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id_alcance_masivo", unique = true, nullable = false)
    public int getIdAlcanceMasivo() {
        return this.idAlcanceMasivo;
    }

    public void setIdAlcanceMasivo(int idAlcanceMasivo) {
        this.idAlcanceMasivo = idAlcanceMasivo;
    }

    @Column(name = "descripcion_alcance", length = 200)
    public String getDescripcionAlcance() {
        return this.descripcionAlcance;
    }

    public void setDescripcionAlcance(String descripcionAlcance) {
        this.descripcionAlcance = descripcionAlcance;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "fecha_modifica", nullable = false, length = 22)
    public Date getFechaModifica() {
        return this.fechaModifica;
    }

    public void setFechaModifica(Date fechaModifica) {
        this.fechaModifica = fechaModifica;
    }

    @Column(name = "ip_modifica", nullable = false, length = 40)
    public String getIpModifica() {
        return this.ipModifica;
    }

    public void setIpModifica(String ipModifica) {
        this.ipModifica = ipModifica;
    }

    @Column(name = "nombre_alcance", nullable = false, length = 50)
    public String getNombreAlcance() {
        return this.nombreAlcance;
    }

    public void setNombreAlcance(String nombreAlcance) {
        this.nombreAlcance = nombreAlcance;
    }

    @Column(name = "usuario_modifica", nullable = false, length = 20)
    public String getUsuarioModifica() {
        return this.usuarioModifica;
    }

    public void setUsuarioModifica(String usuarioModifica) {
        this.usuarioModifica = usuarioModifica;
    }

}
