package gt.gob.sat.sat_ifi_sipf.models;
// Generated Oct 18, 2022 10:22:42 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import lombok.Builder;

/**
 * SipfInconsistencia generated by hbm2java
 */
@Builder
@Entity
@Table(name="sipf_inconsistencia"
    ,schema="sat_ifi_sipf"
)
public class SipfInconsistencia  implements java.io.Serializable {


     private int idInconsistencia;
     private int numeroDeclaracion;
     private int tipoInconsistencia;
     private String descripcion;
     private Date fechaGrabacion;
     private String usuarioGrabacion;
     private int numeroSolicitud;
     private Integer tipoRepetida;
     private Integer declaracionRepetida;
     private String facturaProveedor;
     private String facturaSerie;
     private String facturaNumero;
     private Integer estado;

    public SipfInconsistencia() {
    }

	
    public SipfInconsistencia(int idInconsistencia, int numeroDeclaracion, int tipoInconsistencia, String descripcion, Date fechaGrabacion, String usuarioGrabacion, int numeroSolicitud, Integer estado) {
        this.idInconsistencia = idInconsistencia;
        this.numeroDeclaracion = numeroDeclaracion;
        this.tipoInconsistencia = tipoInconsistencia;
        this.descripcion = descripcion;
        this.fechaGrabacion = fechaGrabacion;
        this.usuarioGrabacion = usuarioGrabacion;
        this.numeroSolicitud = numeroSolicitud;
        this.estado = estado;
    }
    public SipfInconsistencia(int idInconsistencia, int numeroDeclaracion, int tipoInconsistencia, String descripcion, Date fechaGrabacion, String usuarioGrabacion, int numeroSolicitud, Integer tipoRepetida, Integer declaracionRepetida, String facturaProveedor, String facturaSerie, String facturaNumero, Integer estado) {
       this.idInconsistencia = idInconsistencia;
       this.numeroDeclaracion = numeroDeclaracion;
       this.tipoInconsistencia = tipoInconsistencia;
       this.descripcion = descripcion;
       this.fechaGrabacion = fechaGrabacion;
       this.usuarioGrabacion = usuarioGrabacion;
       this.numeroSolicitud = numeroSolicitud;
       this.tipoRepetida = tipoRepetida;
       this.declaracionRepetida = declaracionRepetida;
       this.facturaProveedor = facturaProveedor;
       this.facturaSerie = facturaSerie;
       this.facturaNumero = facturaNumero;
       this.estado = estado;
    }
   
     @Id 

    
    @Column(name="id_inconsistencia", unique=true, nullable=false)
    public int getIdInconsistencia() {
        return this.idInconsistencia;
    }
    
    public void setIdInconsistencia(int idInconsistencia) {
        this.idInconsistencia = idInconsistencia;
    }

    
    @Column(name="numero_declaracion", nullable=false)
    public int getNumeroDeclaracion() {
        return this.numeroDeclaracion;
    }
    
    public void setNumeroDeclaracion(int numeroDeclaracion) {
        this.numeroDeclaracion = numeroDeclaracion;
    }

    
    @Column(name="tipo_inconsistencia", nullable=false)
    public int getTipoInconsistencia() {
        return this.tipoInconsistencia;
    }
    
    public void setTipoInconsistencia(int tipoInconsistencia) {
        this.tipoInconsistencia = tipoInconsistencia;
    }

    
    @Column(name="descripcion", nullable=false, length=200)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha_grabacion", nullable=false, length=13)
    public Date getFechaGrabacion() {
        return this.fechaGrabacion;
    }
    
    public void setFechaGrabacion(Date fechaGrabacion) {
        this.fechaGrabacion = fechaGrabacion;
    }

    
    @Column(name="usuario_grabacion", nullable=false, length=10)
    public String getUsuarioGrabacion() {
        return this.usuarioGrabacion;
    }
    
    public void setUsuarioGrabacion(String usuarioGrabacion) {
        this.usuarioGrabacion = usuarioGrabacion;
    }

    
    @Column(name="numero_solicitud", nullable=false)
    public int getNumeroSolicitud() {
        return this.numeroSolicitud;
    }
    
    public void setNumeroSolicitud(int numeroSolicitud) {
        this.numeroSolicitud = numeroSolicitud;
    }

    
    @Column(name="tipo_repetida")
    public Integer getTipoRepetida() {
        return this.tipoRepetida;
    }
    
    public void setTipoRepetida(Integer tipoRepetida) {
        this.tipoRepetida = tipoRepetida;
    }

    
    @Column(name="declaracion_repetida")
    public Integer getDeclaracionRepetida() {
        return this.declaracionRepetida;
    }
    
    public void setDeclaracionRepetida(Integer declaracionRepetida) {
        this.declaracionRepetida = declaracionRepetida;
    }

    
    @Column(name="factura_proveedor", length=16)
    public String getFacturaProveedor() {
        return this.facturaProveedor;
    }
    
    public void setFacturaProveedor(String facturaProveedor) {
        this.facturaProveedor = facturaProveedor;
    }

    
    @Column(name="factura_serie", length=100)
    public String getFacturaSerie() {
        return this.facturaSerie;
    }
    
    public void setFacturaSerie(String facturaSerie) {
        this.facturaSerie = facturaSerie;
    }

    
    @Column(name="factura_numero", length=100)
    public String getFacturaNumero() {
        return this.facturaNumero;
    }
    
    public void setFacturaNumero(String facturaNumero) {
        this.facturaNumero = facturaNumero;
    }

    @Column(name="estado")
    public Integer getEstado() {
        return estado;
    }

    public void setEstado(Integer estado) {
        this.estado = estado;
    }




}


