package gt.gob.sat.sat_ifi_sipf.models;
// Generated 13-ene-2023 9:26:02 by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import lombok.Builder;

/**
 * SipfBitacoraProgramasFiscales generated by hbm2java
 */
@Entity
@Builder
@Table(name = "sipf_bitacora_programas_fiscales",
         schema = "sat_ifi_sipf"
)
public class SipfBitacoraProgramasFiscales implements java.io.Serializable {

    private int id;
    private int idPrograma;
    private int idTipoOperacion;
    private String usuarioModifica;
    private Date fechaModifica;
    private int idEstadoAnterior;
    private int idEstadoNuevo;

    public SipfBitacoraProgramasFiscales() {
    }

    public SipfBitacoraProgramasFiscales(int id, int idPrograma, int idTipoOperacion, String usuarioModifica, Date fechaModifica, int idEstadoAnterior, int idEstadoNuevo) {
        this.id = id;
        this.idPrograma = idPrograma;
        this.idTipoOperacion = idTipoOperacion;
        this.usuarioModifica = usuarioModifica;
        this.fechaModifica = fechaModifica;
        this.idEstadoAnterior = idEstadoAnterior;
        this.idEstadoNuevo = idEstadoNuevo;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @Column(name = "id_programa", nullable = false)
    public int getIdPrograma() {
        return this.idPrograma;
    }

    public void setIdPrograma(int idPrograma) {
        this.idPrograma = idPrograma;
    }

    @Column(name = "id_tipo_operacion", nullable = false)
    public int getIdTipoOperacion() {
        return this.idTipoOperacion;
    }

    public void setIdTipoOperacion(int idTipoOperacion) {
        this.idTipoOperacion = idTipoOperacion;
    }

    @Column(name = "usuario_modifica", nullable = false, length = 20)
    public String getUsuarioModifica() {
        return this.usuarioModifica;
    }

    public void setUsuarioModifica(String usuarioModifica) {
        this.usuarioModifica = usuarioModifica;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "fecha_modifica", nullable = false, length = 29)
    public Date getFechaModifica() {
        return this.fechaModifica;
    }

    public void setFechaModifica(Date fechaModifica) {
        this.fechaModifica = fechaModifica;
    }

    @Column(name = "id_estado_anterior", nullable = false)
    public int getIdEstadoAnterior() {
        return this.idEstadoAnterior;
    }

    public void setIdEstadoAnterior(int idEstadoAnterior) {
        this.idEstadoAnterior = idEstadoAnterior;
    }

    @Column(name = "id_estado_nuevo", nullable = false)
    public int getIdEstadoNuevo() {
        return this.idEstadoNuevo;
    }

    public void setIdEstadoNuevo(int idEstadoNuevo) {
        this.idEstadoNuevo = idEstadoNuevo;
    }

}
