package gt.gob.sat.sat_ifi_sipf.models;
// Generated 1/02/2022 09:34:44 AM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SipfImpuestoPrograma generated by hbm2java
 */
@Entity
@Table(name = "sipf_impuesto_programa",
        schema = "sat_ifi_sipf"
)
public class SipfImpuestoPrograma implements java.io.Serializable {

    private SipfImpuestoProgramaId id;
    private String usuarioModifica;
    private String ipModifica;
    private Date fechaModifica;

    public SipfImpuestoPrograma() {
    }

    public SipfImpuestoPrograma(SipfImpuestoProgramaId id, String usuarioModifica, String ipModifica, Date fechaModifica) {
        this.id = id;
        this.usuarioModifica = usuarioModifica;
        this.ipModifica = ipModifica;
        this.fechaModifica = fechaModifica;
    }

    @EmbeddedId

    @AttributeOverrides({
        @AttributeOverride(name = "idPrograma", column = @Column(name = "id_programa", nullable = false))
        , 
        @AttributeOverride(name = "idImpuesto", column = @Column(name = "id_impuesto", nullable = false))})
    public SipfImpuestoProgramaId getId() {
        return this.id;
    }

    public void setId(SipfImpuestoProgramaId id) {
        this.id = id;
    }

    @Column(name = "usuario_modifica", nullable = false, length = 20)
    public String getUsuarioModifica() {
        return this.usuarioModifica;
    }

    public void setUsuarioModifica(String usuarioModifica) {
        this.usuarioModifica = usuarioModifica;
    }

    @Column(name = "ip_modifica", nullable = false, length = 40)
    public String getIpModifica() {
        return this.ipModifica;
    }

    public void setIpModifica(String ipModifica) {
        this.ipModifica = ipModifica;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "fecha_modifica", nullable = false, length = 22)
    public Date getFechaModifica() {
        return this.fechaModifica;
    }

    public void setFechaModifica(Date fechaModifica) {
        this.fechaModifica = fechaModifica;
    }

}
