package gt.gob.sat.sat_ifi_sipf.models;
// Generated 1/02/2022 09:34:44 AM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SipfImpuestoProgramaId generated by hbm2java
 */
@Embeddable
public class SipfImpuestoProgramaId implements java.io.Serializable {

    private int idPrograma;
    private int idImpuesto;

    public SipfImpuestoProgramaId() {
    }

    public SipfImpuestoProgramaId(int idPrograma, int idImpuesto) {
        this.idPrograma = idPrograma;
        this.idImpuesto = idImpuesto;
    }

    @Column(name = "id_programa", nullable = false)
    public int getIdPrograma() {
        return this.idPrograma;
    }

    public void setIdPrograma(int idPrograma) {
        this.idPrograma = idPrograma;
    }

    @Column(name = "id_impuesto", nullable = false)
    public int getIdImpuesto() {
        return this.idImpuesto;
    }

    public void setIdImpuesto(int idImpuesto) {
        this.idImpuesto = idImpuesto;
    }

    public boolean equals(Object other) {
        if ((this == other)) {
            return true;
        }
        if ((other == null)) {
            return false;
        }
        if (!(other instanceof SipfImpuestoProgramaId)) {
            return false;
        }
        SipfImpuestoProgramaId castOther = (SipfImpuestoProgramaId) other;

        return (this.getIdPrograma() == castOther.getIdPrograma())
                && (this.getIdImpuesto() == castOther.getIdImpuesto());
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + this.getIdPrograma();
        result = 37 * result + this.getIdImpuesto();
        return result;
    }

}
