package gt.gob.sat.sat_ifi_sipf.models;
// Generated 1/02/2022 09:24:51 AM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SipfCatCatalogo generated by hbm2java
 */
@Entity
@Table(name = "sipf_cat_catalogo",
        schema = "sat_ifi_sipf"
)
public class SipfCatCatalogo implements java.io.Serializable {

    private int codigo;
    private SipfCatCatalogo sipfCatCatalogo;
    private String nombre;
    private String descripcion;
    private Integer estado;
    private String usuarioAgrega;
    private Date fechaAgrega;
    private String usuarioModifica;
    private Date fechaModifica;
    private Set<SipfCatCatalogo> sipfCatCatalogos = new HashSet<SipfCatCatalogo>(0);

    public SipfCatCatalogo() {
    }

    public SipfCatCatalogo(int codigo) {
        this.codigo = codigo;
    }

    public SipfCatCatalogo(int codigo, SipfCatCatalogo sipfCatCatalogo, String nombre, String descripcion, Integer estado, String usuarioAgrega, Date fechaAgrega, String usuarioModifica, Date fechaModifica, Set<SipfCatCatalogo> sipfCatCatalogos) {
        this.codigo = codigo;
        this.sipfCatCatalogo = sipfCatCatalogo;
        this.nombre = nombre;
        this.descripcion = descripcion;
        this.estado = estado;
        this.usuarioAgrega = usuarioAgrega;
        this.fechaAgrega = fechaAgrega;
        this.usuarioModifica = usuarioModifica;
        this.fechaModifica = fechaModifica;
        this.sipfCatCatalogos = sipfCatCatalogos;
    }

    @Id

    @Column(name = "codigo", unique = true, nullable = false)
    public int getCodigo() {
        return this.codigo;
    }

    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "codigo_cat_padre")
    public SipfCatCatalogo getSipfCatCatalogo() {
        return this.sipfCatCatalogo;
    }

    public void setSipfCatCatalogo(SipfCatCatalogo sipfCatCatalogo) {
        this.sipfCatCatalogo = sipfCatCatalogo;
    }

    @Column(name = "nombre")
    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    @Column(name = "descripcion")
    public String getDescripcion() {
        return this.descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    @Column(name = "estado")
    public Integer getEstado() {
        return this.estado;
    }

    public void setEstado(Integer estado) {
        this.estado = estado;
    }

    @Column(name = "usuario_agrega")
    public String getUsuarioAgrega() {
        return this.usuarioAgrega;
    }

    public void setUsuarioAgrega(String usuarioAgrega) {
        this.usuarioAgrega = usuarioAgrega;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "fecha_agrega", length = 29)
    public Date getFechaAgrega() {
        return this.fechaAgrega;
    }

    public void setFechaAgrega(Date fechaAgrega) {
        this.fechaAgrega = fechaAgrega;
    }

    @Column(name = "usuario_modifica")
    public String getUsuarioModifica() {
        return this.usuarioModifica;
    }

    public void setUsuarioModifica(String usuarioModifica) {
        this.usuarioModifica = usuarioModifica;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "fecha_modifica", length = 29)
    public Date getFechaModifica() {
        return this.fechaModifica;
    }

    public void setFechaModifica(Date fechaModifica) {
        this.fechaModifica = fechaModifica;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "sipfCatCatalogo")
    public Set<SipfCatCatalogo> getSipfCatCatalogos() {
        return this.sipfCatCatalogos;
    }

    public void setSipfCatCatalogos(Set<SipfCatCatalogo> sipfCatCatalogos) {
        this.sipfCatCatalogos = sipfCatCatalogos;
    }

}
